/**
 *
 * _  __           _    _
 * | |/ /___   ___ | | _(_) ___
 * | ' // _ \ / _ \| |/ / |/ _ \
 * | . \ (_) | (_) |   <| |  __/
 * |_|\_\___/ \___/|_|\_\_|\___|
 *
 * A server software for Minecraft: Bedrock Edition
 *
 * Copyright (C) 2021 organization Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package be.zvz.kookie.network.mcpe.protocol.types.entity

enum class EntityIds(val id: Int, val value: String) {
    AGENT(56, "minecraft:agent"),
    AREA_EFFECT_CLOUD(95, "minecraft:area_effect_cloud"),
    ARMOR_STAND(61, "minecraft:armor_stand"),
    ARROW(80, "minecraft:arrow"),
    BALLOON(107, "minecraft:balloon"),
    BAT(19, "minecraft:bat"),
    BEE(122, "minecraft:bee"),
    BLAZE(43, "minecraft:blaze"),
    BOAT(90, "minecraft:boat"),
    CAT(75, "minecraft:cat"),
    CAVE_SPIDER(40, "minecraft:cave_spider"),
    CHALKBOARD(78, "minecraft:chalkboard"),
    CHEST_MINECART(98, "minecraft:chest_minecart"),
    CHICKEN(10, "minecraft:chicken"),
    COD(112, "minecraft:cod"),
    COMMAND_BLOCK_MINECART(100, "minecraft:command_block_minecart"),
    COW(11, "minecraft:cow"),
    CREEPER(33, "minecraft:creeper"),
    DOLPHIN(31, "minecraft:dolphin"),
    DONKEY(24, "minecraft:donkey"),
    DRAGON_FIREBALL(79, "minecraft:dragon_fireball"),
    DROWNED(110, "minecraft:drowned"),
    EGG(82, "minecraft:egg"),
    ELDER_GUARDIAN(50, "minecraft:elder_guardian"),
    ELDER_GUARDIAN_GHOST(120, "minecraft:elder_guardian_ghost"),
    ENDERMAN(38, "minecraft:enderman"),
    ENDERMITE(55, "minecraft:endermite"),
    ENDER_CRYSTAL(71, "minecraft:ender_crystal"),
    ENDER_DRAGON(53, "minecraft:ender_dragon"),
    ENDER_PEARL(87, "minecraft:ender_pearl"),
    EVOCATION_FANG(103, "minecraft:evocation_fang"),
    EVOCATION_ILLAGER(104, "minecraft:evocation_illager"),
    EYE_OF_ENDER_SIGNAL(70, "minecraft:eye_of_ender_signal"),
    FALLING_BLOCK(66, "minecraft:falling_block"),
    FIREBALL(85, "minecraft:fireball"),
    FIREWORKS_ROCKET(72, "minecraft:fireworks_rocket"),
    FISHING_HOOK(77, "minecraft:fishing_hook"),
    FOX(121, "minecraft:fox"),
    GHAST(41, "minecraft:ghast"),
    GOAT(128, "minecraft:goat"),
    GUARDIAN(49, "minecraft:guardian"),
    HEEP(13, "minecraft:heep"),
    HOGLIN(124, "minecraft:hoglin"),
    HOPPER_MINECART(96, "minecraft:hopper_minecart"),
    HORSE(23, "minecraft:horse"),
    HUSK(47, "minecraft:husk"),
    ICE_BOMB(106, "minecraft:ice_bomb"),
    IG(12, "minecraft:ig"),
    ILLAGER(15, "minecraft:illager"),
    IRON_GOLEM(20, "minecraft:iron_golem"),
    ITEM(64, "minecraft:item"),
    LEASH_KNOT(88, "minecraft:leash_knot"),
    LIGHTNING_BOLT(93, "minecraft:lightning_bolt"),
    LINGERING_POTION(101, "minecraft:lingering_potion"),
    LLAMA(29, "minecraft:llama"),
    LLAMA_SPIT(102, "minecraft:llama_spit"),
    MAGMA_CUBE(42, "minecraft:magma_cube"),
    MINECART(84, "minecraft:minecart"),
    MOOSHROOM(16, "minecraft:mooshroom"),
    MOVING_BLOCK(67, "minecraft:moving_block"),
    MULE(25, "minecraft:mule"),
    NPC(51, "minecraft:npc"),
    OCELOT(22, "minecraft:ocelot"),
    OLF(14, "minecraft:olf"),
    OW(11, "minecraft:ow"),
    PAINTING(83, "minecraft:painting"),
    PANDA(113, "minecraft:panda"),
    PARROT(30, "minecraft:parrot"),
    PHANTOM(58, "minecraft:phantom"),
    PIGLIN(123, "minecraft:piglin"),
    PIGLIN_BRUTE(127, "minecraft:piglin_brute"),
    PILLAGER(114, "minecraft:pillager"),
    PLAYER(63, "minecraft:player"),
    POLAR_BEAR(28, "minecraft:polar_bear"),
    PUFFERFISH(108, "minecraft:pufferfish"),
    RABBIT(18, "minecraft:rabbit"),
    RAVAGER(59, "minecraft:ravager"),
    SALMON(109, "minecraft:salmon"),
    SHEEP(13, "minecraft:sheep"),
    SHIELD(117, "minecraft:shield"),
    SHULKER(54, "minecraft:shulker"),
    SHULKER_BULLET(76, "minecraft:shulker_bullet"),
    SILVERFISH(39, "minecraft:silverfish"),
    SKELETON(34, "minecraft:skeleton"),
    SKELETON_HORSE(26, "minecraft:skeleton_horse"),
    SLIME(37, "minecraft:slime"),
    SMALL_FIREBALL(94, "minecraft:small_fireball"),
    SNOWBALL(81, "minecraft:snowball"),
    SNOW_GOLEM(21, "minecraft:snow_golem"),
    SPIDER(35, "minecraft:spider"),
    SPLASH_POTION(86, "minecraft:splash_potion"),
    SQUID(17, "minecraft:squid"),
    STRAY(46, "minecraft:stray"),
    STRIDER(125, "minecraft:strider"),
    THROWN_TRIDENT(73, "minecraft:thrown_trident"),
    TNT(65, "minecraft:tnt"),
    TNT_MINECART(97, "minecraft:tnt_minecart"),
    TRIPOD_CAMERA(62, "minecraft:tripod_camera"),
    TROPICALFISH(111, "minecraft:tropicalfish"),
    TURTLE(74, "minecraft:turtle"),
    VEX(105, "minecraft:vex"),
    VILLAGER(15, "minecraft:villager"),
    VILLAGER_V2(115, "minecraft:villager_v2"),
    VINDICATOR(57, "minecraft:vindicator"),
    WANDERING_TRADER(118, "minecraft:wandering_trader"),
    WITCH(45, "minecraft:witch"),
    WITHER(52, "minecraft:wither"),
    WITHER_SKELETON(48, "minecraft:wither_skeleton"),
    WITHER_SKULL(89, "minecraft:wither_skull"),
    WITHER_SKULL_DANGEROUS(91, "minecraft:wither_skull_dangerous"),
    WOLF(14, "minecraft:wolf"),
    XP_BOTTLE(68, "minecraft:xp_bottle"),
    XP_ORB(69, "minecraft:xp_orb"),
    ZOGLIN(126, "minecraft:zoglin"),
    ZOMBIE(32, "minecraft:zombie"),
    ZOMBIE_HORSE(27, "minecraft:zombie_horse"),
    ZOMBIE_PIGMAN(36, "minecraft:zombie_pigman"),
    ZOMBIE_VILLAGER(44, "minecraft:zombie_villager"),
    ZOMBIE_VILLAGER_V2(116, "minecraft:zombie_villager_v2"),
}
