/**
 *
 * _  __           _    _
 * | |/ /___   ___ | | _(_) ___
 * | ' // _ \ / _ \| |/ / |/ _ \
 * | . \ (_) | (_) |   <| |  __/
 * |_|\_\___/ \___/|_|\_\_|\___|
 *
 * A server software for Minecraft: Bedrock Edition
 *
 * Copyright (C) 2021 organization Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package be.zvz.kookie.block

enum class VanillaBlocks(val block: Block) {
    AIR(BlockFactory.get(0, 0)),
    STONE(BlockFactory.get(1, 0)),
    GRANITE(BlockFactory.get(1, 1)),
    POLISHED_GRANITE(BlockFactory.get(1, 2)),
    DIORITE(BlockFactory.get(1, 3)),
    POLISHED_DIORITE(BlockFactory.get(1, 4)),
    ANDESITE(BlockFactory.get(1, 5)),
    POLISHED_ANDESITE(BlockFactory.get(1, 6)),
    GRASS(BlockFactory.get(2, 0)),
    DIRT(BlockFactory.get(3, 0)),
    COBBLESTONE(BlockFactory.get(4, 0)),

    PLANKS(BlockFactory.get(5, 0)),
    OAK_PLANKS(BlockFactory.get(5, 0)),
    SPRUCE_PLANKS(BlockFactory.get(5, 1)),
    BIRCH_PLANKS(BlockFactory.get(5, 2)),
    JUNGLE_PLANKS(BlockFactory.get(5, 3)),
    ACACIA_PLANKS(BlockFactory.get(5, 4)),
    DARK_OAK_PLANKS(BlockFactory.get(5, 5)),

    SAPLING(BlockFactory.get(6, 0)),
    OAK_SAPLING(BlockFactory.get(6, 0)),
    SPRUCE_SAPLING(BlockFactory.get(6, 1)),
    BIRCH_SAPLING(BlockFactory.get(6, 2)),
    JUNGLE_SAPLING(BlockFactory.get(6, 3)),
    ACACIA_SAPLING(BlockFactory.get(6, 4)),
    DARK_OAK_SAPLING(BlockFactory.get(6, 5)),

    BEDROCK(BlockFactory.get(7, 0)),

    FLOWING_WATER(BlockFactory.get(8, 0)),
    WATER(BlockFactory.get(9, 0)),
    FLOWING_LAVA(BlockFactory.get(10, 0)),
    LAVA(BlockFactory.get(11, 0)),

    SAND(BlockFactory.get(12, 0)),
    RED_SAND(BlockFactory.get(12, 1)),
    GRAVEL(BlockFactory.get(13, 0)),
    GOLD_ORE(BlockFactory.get(14, 0)),
    IRON_ORE(BlockFactory.get(15, 0)),
    COAL_ORE(BlockFactory.get(16, 0)),

    LOG(BlockFactory.get(17, 0)),
    OAK_LOG(BlockFactory.get(17, 0)),
    SPRUCE_LOG(BlockFactory.get(17, 1)),
    BIRCH_LOG(BlockFactory.get(17, 2)),
    JUNGLE_LOG(BlockFactory.get(17, 3)),

    LEAVES(BlockFactory.get(18, 0)),
    OAK_LEAVES(BlockFactory.get(18, 0)),
    SPRUCE_LEAVES(BlockFactory.get(18, 1)),
    BIRCH_LEAVES(BlockFactory.get(18, 2)),
    JUNGLE_LEAVES(BlockFactory.get(18, 3)),

    SPONGE(BlockFactory.get(19, 0)),
    GLASS(BlockFactory.get(20, 0)),

    LAPIS_LAZULI_ORE(BlockFactory.get(21, 0)),
    LAPIS_LAZULI_BLOCK(BlockFactory.get(22, 0)),

    DISPENSER(BlockFactory.get(23, 0)),

    SANDSTONE(BlockFactory.get(24, 0)),
    CHISELED_SANDSTONE(BlockFactory.get(24, 1)),
    CUT_SANDSTONE(BlockFactory.get(24, 2)),
    SMOOTH_SANDSTONE(BlockFactory.get(24, 3)),

    NOTE_BLOCK(BlockFactory.get(25, 0)),
    BED(BlockFactory.get(26, 0)),

    POWERED_RAIL(BlockFactory.get(27, 0)),
    DETECTOR_RAIL(BlockFactory.get(28, 0)),
    STICKY_PISTON(BlockFactory.get(29, 0)),

    COBWEB(BlockFactory.get(30, 0)),

    TALL_GRASS(BlockFactory.get(31, 1)),
    FERN(BlockFactory.get(31, 2)),
    DEAD_BUSH(BlockFactory.get(32, 0)),

    PISTON(BlockFactory.get(33, 0)),
    PISTON_HEAD(BlockFactory.get(34, 0)),

    WOOL(BlockFactory.get(35, 0)),
    WHITE_WOOL(BlockFactory.get(35, 0)),
    ORANGE_WOOL(BlockFactory.get(35, 1)),
    MAGENTA_WOOL(BlockFactory.get(35, 2)),
    LIGHT_BLUE_WOOL(BlockFactory.get(35, 3)),
    YELLOW_WOOL(BlockFactory.get(35, 4)),
    LIME_WOOL(BlockFactory.get(35, 5)),
    PINK_WOOL(BlockFactory.get(35, 6)),
    GRAY_WOOL(BlockFactory.get(35, 7)),
    LIGHT_GRAY_WOOL(BlockFactory.get(35, 8)),
    CYAN_WOOL(BlockFactory.get(35, 9)),
    PURPLE_WOOL(BlockFactory.get(35, 10)),
    BLUE_WOOL(BlockFactory.get(35, 11)),
    BROWN_WOOL(BlockFactory.get(35, 12)),
    GREEN_WOOL(BlockFactory.get(35, 13)),
    RED_WOOL(BlockFactory.get(35, 14)),
    BLACK_WOOL(BlockFactory.get(35, 15)),

    ELEMENT_0(BlockFactory.get(36, 0)),
    UNKNOWN_ELEMENT(BlockFactory.get(36, 0)),

    YELLOW_FLOWER(BlockFactory.get(37, 0)),
    DANDELION(BlockFactory.get(37, 0)),

    RED_FLOWER(BlockFactory.get(38, 0)),
    POPPY(BlockFactory.get(38, 0)),
    BLUE_ORCHID(BlockFactory.get(38, 1)),
    ALLIUM(BlockFactory.get(38, 2)),
    AZURE_BLUET(BlockFactory.get(38, 3)),
    RED_TULIP(BlockFactory.get(38, 4)),
    ORANGE_TULIP(BlockFactory.get(38, 5)),
    WHITE_TULIP(BlockFactory.get(38, 6)),
    PINK_TULIP(BlockFactory.get(38, 7)),
    OXEYE_DAISY(BlockFactory.get(38, 8)),
    CORNFLOWER(BlockFactory.get(38, 9)),
    LILY_OF_THE_VALLEY(BlockFactory.get(38, 10)),

    BROWN_MUSHROOM(BlockFactory.get(39, 0)),
    RED_MUSHROOM(BlockFactory.get(40, 0)),

    GOLD_BLOCK(BlockFactory.get(41, 0)),
    BLOCK_OF_GOLD(BlockFactory.get(41, 0)),

    IRON_BLOCK(BlockFactory.get(42, 0)),
    BLOCK_OF_IRON(BlockFactory.get(42, 0)),

    DOUBLE_STONE_SLAB(BlockFactory.get(43, 0)),
    SMOOTH_STONE_SLAB(BlockFactory.get(44, 0)),
    SANDSTONE_SLAB(BlockFactory.get(44, 1)),
    FAKE_WOODEN_SLAB(BlockFactory.get(44, 2)),
    COBBLESTONE_SLAB(BlockFactory.get(44, 3)),
    BRICK_SLAB(BlockFactory.get(44, 4)),
    STONE_BRICK_SLAB(BlockFactory.get(44, 5)),
    QUARTZ_SLAB(BlockFactory.get(44, 6)),
    NETHER_BRICK_SLAB(BlockFactory.get(44, 7)),

    BRICK_BLOCK(BlockFactory.get(45, 0)),
    TNT(BlockFactory.get(46, 0)),
    BOOKSHELF(BlockFactory.get(47, 0)),
    MOSSY_COBBLESTONE(BlockFactory.get(48, 0)),
    OBSIDIAN(BlockFactory.get(49, 0)),
    TORCH(BlockFactory.get(50, 5)),
    FIRE(BlockFactory.get(51, 0)),
    SPAWNER(BlockFactory.get(52, 0)),
    OAK_STAIRS(BlockFactory.get(53, 0)),
    CHEST(BlockFactory.get(54, 2)),
    REDSTONE_WIRE(BlockFactory.get(55, 0)),
    DIAMOND_ORE(BlockFactory.get(56, 0)),

    DIAMOND_BLOCK(BlockFactory.get(57, 0)),
    BLOCK_OF_DIAMOND(BlockFactory.get(57, 0)),

    CRAFTING_TABLE(BlockFactory.get(58, 0)),
    WHEAT_CROPS(BlockFactory.get(59, 0)),
    FARMLAND(BlockFactory.get(60, 0)),

    FURNACE(BlockFactory.get(61, 2)),
    LIT_FURNACE(BlockFactory.get(62, 2)),

    OAK_STANDING_SIGN(BlockFactory.get(63, 0)),
    OAK_DOOR(BlockFactory.get(64, 0)),
    LADDER(BlockFactory.get(65, 2)),
    RAIL(BlockFactory.get(66, 0)),
    COBBLESTONE_STAIRS(BlockFactory.get(67, 0)),
    OAK_WALL_SIGN(BlockFactory.get(68, 2)),
    LEVER(BlockFactory.get(69, 0)),
    STONE_PRESSURE_PLATE(BlockFactory.get(70, 0)),
    IRON_DOOR(BlockFactory.get(71, 0)),
    OAK_PRESSURE_PLATE(BlockFactory.get(72, 0)),
    REDSTONE_ORE(BlockFactory.get(73, 0)),

    LIT_REDSTONE_ORE(BlockFactory.get(74, 0)),
    GLOWING_REDSTONE_ORE(BlockFactory.get(74, 0)),

    UNLIT_REDSTONE_TORCH(BlockFactory.get(75, 0)),
    REDSTONE_TORCH(BlockFactory.get(76, 5)),

    STONE_BUTTON(BlockFactory.get(77, 0)),
    SNOW_LAYER(BlockFactory.get(78, 0)),
    ICE(BlockFactory.get(79, 0)),
    SNOW(BlockFactory.get(80, 0)),
    CACTUS(BlockFactory.get(81, 0)),
    CLAY(BlockFactory.get(82, 0)),
    SUGAR_CANE(BlockFactory.get(83, 0)),
    JUKEBOX(BlockFactory.get(84, 0)),

    FENCE(BlockFactory.get(85, 0)),
    OAK_FENCE(BlockFactory.get(85, 0)),
    SPRUCE_FENCE(BlockFactory.get(85, 1)),
    BIRCH_FENCE(BlockFactory.get(85, 2)),
    JUNGLE_FENCE(BlockFactory.get(85, 3)),
    ACACIA_FENCE(BlockFactory.get(85, 4)),
    DARK_OAK_FENCE(BlockFactory.get(85, 5)),

    PUMPKIN(BlockFactory.get(86, 0)),
    NETHERRACK(BlockFactory.get(87, 0)),
    SOUL_SAND(BlockFactory.get(88, 0)),
    GLOWSTONE(BlockFactory.get(89, 0)),
    PORTAL(BlockFactory.get(90, 0)),
    NETHER_PORTAL(BlockFactory.get(90, 1)),

    LIT_PUMPKIN(BlockFactory.get(91, 0)),
    JACK_O_LANTERN(BlockFactory.get(91, 0)),
    CAKE(BlockFactory.get(92, 0)),

    REDSTONE_REPEATER(BlockFactory.get(93, 0)),
    UNPOWERED_REPEATER(BlockFactory.get(93, 0)),
    POWERED_REPEATER(BlockFactory.get(94, 0)),

    INVISIBLE_BEDROCK(BlockFactory.get(95, 0)),
    OAK_TRAPDOOR(BlockFactory.get(96, 0)),

    INFESTED_STONE(BlockFactory.get(97, 0)),
    INFESTED_COBBLESTONE(BlockFactory.get(97, 1)),
    INFESTED_STONE_BRICKS(BlockFactory.get(97, 2)),
    INFESTED_MOSSY_STONE_BRICKS(BlockFactory.get(97, 3)),
    INFESTED_CRACKED_STONE_BRICKS(BlockFactory.get(97, 4)),
    INFESTED_CHISELED_STONE_BRICKS(BlockFactory.get(97, 5)),
    INFESTED_DEEPSLATE(BlockFactory.get(97, 6)),

    STONE_BRICKS(BlockFactory.get(98, 0)),
    MOSSY_STONE_BRICKS(BlockFactory.get(98, 1)),
    CRACKED_STONE_BRICKS(BlockFactory.get(98, 2)),
    CHISELED_STONE_BRICKS(BlockFactory.get(98, 3)),
    SMOOTH_STONE_BRICKS(BlockFactory.get(98, 4)),

    BROWN_MUSHROOM_BLOCK(BlockFactory.get(99, 0)),
    MUSHROOM_STEM(BlockFactory.get(99, 10)),
    ALL_SIDED_MUSHROOM_STEM(BlockFactory.get(99, 15)),
    RED_MUSHROOM_BLOCK(BlockFactory.get(100, 0)),

    IRON_BARS(BlockFactory.get(101, 0)),
    GLASS_PANE(BlockFactory.get(102, 0)),
    MELON(BlockFactory.get(103, 0)),
    PUMPKIN_STEM(BlockFactory.get(104, 0)),
    MELON_STEM(BlockFactory.get(105, 0)),
    VINES(BlockFactory.get(106, 0)),
    OAK_FENCE_GATE(BlockFactory.get(107, 0)),
    BRICK_STAIRS(BlockFactory.get(108, 0)),
    STONE_BRICK_STAIRS(BlockFactory.get(109, 0)),
    MYCELIUM(BlockFactory.get(110, 0)),
    LILY_PAD(BlockFactory.get(111, 0)),
    NETHER_BRICK(BlockFactory.get(112, 0)),
    NETHER_BRICK_FENCE(BlockFactory.get(113, 0)),
    NETHER_BRICK_STAIRS(BlockFactory.get(114, 0)),
    NETHER_WART(BlockFactory.get(115, 0)),
    ENCHANTING_TABLE(BlockFactory.get(116, 0)),
    BREWING_STAND(BlockFactory.get(117, 0)),
    CAULDRON(BlockFactory.get(118, 0)),
    END_PORTAL(BlockFactory.get(119, 0)),
    END_PORTAL_FRAME(BlockFactory.get(120, 0)),
    END_STONE(BlockFactory.get(121, 0)),
    DRAGON_EGG(BlockFactory.get(122, 0)),
    REDSTONE_LAMP(BlockFactory.get(123, 0)),
    LIT_REDSTONE_LAMP(BlockFactory.get(124, 0)),
    DROPPER(BlockFactory.get(125, 0)),
    ACTIVATOR_RAIL(BlockFactory.get(126, 0)),
    COCOA(BlockFactory.get(127, 0)),
    SANDSTONE_STAIRS(BlockFactory.get(128, 0)),
    EMERALD_ORE(BlockFactory.get(129, 0)),
    ENDER_CHEST(BlockFactory.get(130, 2)),
    TRIPWIRE_HOOK(BlockFactory.get(131, 0)),
    TRIPWIRE(BlockFactory.get(132, 0)),

    EMERALD_BLOCK(BlockFactory.get(133, 0)),
    BLOCK_OF_EMERALD(BlockFactory.get(133, 0)),

    SPRUCE_STAIRS(BlockFactory.get(134, 0)),
    BIRCH_STAIRS(BlockFactory.get(135, 0)),
    JUNGLE_STAIRS(BlockFactory.get(136, 0)),
    COMMAND_BLOCK(BlockFactory.get(137, 0)),
    BEACON(BlockFactory.get(138, 0)),

    COBBLESTONE_WALL(BlockFactory.get(139, 0)),
    MOSSY_COBBLESTONE_WALL(BlockFactory.get(139, 1)),
    GRANITE_WALL(BlockFactory.get(139, 2)),
    DIORITE_WALL(BlockFactory.get(139, 3)),
    ANDESITE_WALL(BlockFactory.get(139, 4)),
    SANDSTONE_WALL(BlockFactory.get(139, 5)),
    BRICK_WALL(BlockFactory.get(139, 6)),
    STONE_BRICK_WALL(BlockFactory.get(139, 7)),
    MOSSY_STONE_BRICK_WALL(BlockFactory.get(139, 8)),
    NETHER_BRICK_WALL(BlockFactory.get(139, 9)),
    END_STONE_BRICK_WALL(BlockFactory.get(139, 10)),
    PRISMARINE_WALL(BlockFactory.get(139, 11)),
    RED_SANDSTONE_WALL(BlockFactory.get(139, 12)),
    RED_NETHER_BRICK_WALL(BlockFactory.get(139, 13)),

    FLOWER_POT(BlockFactory.get(140, 0)),
    CARROTS(BlockFactory.get(141, 0)),
    POTATOES(BlockFactory.get(142, 0)),
    OAK_BUTTON(BlockFactory.get(143, 0)),

    SKULL(BlockFactory.get(144, 2)),
    HEAD(BlockFactory.get(144, 2)),

    ANVIL(BlockFactory.get(145, 0)),
    TRAPPED_CHEST(BlockFactory.get(146, 2)),

    LIGHT_WEIGHTED_PRESSURE_PLATE(BlockFactory.get(147, 0)),
    HEAVY_WEIGHTED_PRESSURE_PLATE(BlockFactory.get(148, 0)),

    UNPOWERED_COMPARATOR(BlockFactory.get(149, 0)),
    POWERED_COMPARATOR(BlockFactory.get(150, 0)),

    DAYLIGHT_DETECTOR(BlockFactory.get(151, 0)),

    REDSTONE_BLOCK(BlockFactory.get(152, 0)),
    BLOCK_OF_REDSTONE(BlockFactory.get(152, 0)),

    NETHER_QUARTZ_ORE(BlockFactory.get(153, 0)),
    HOPPER(BlockFactory.get(154, 0)),

    QUARTZ_BLOCK(BlockFactory.get(155, 0)),
    BLOCK_OF_QUARTZ(BlockFactory.get(155, 0)),

    CHISELED_QUARTZ_BLOCK(BlockFactory.get(155, 1)),
    PILLAR_QUARTZ_BLOCK(BlockFactory.get(155, 2)),
    SMOOTH_QUARTZ_BLOCK(BlockFactory.get(155, 3)),

    QUARTZ_STAIRS(BlockFactory.get(156, 0)),

    DOUBLE_OAK_SLAB(BlockFactory.get(157, 0)),
    OAK_SLAB(BlockFactory.get(158, 0)),
    SPRUCE_SLAB(BlockFactory.get(158, 1)),
    BIRCH_SLAB(BlockFactory.get(158, 2)),
    JUNGLE_SLAB(BlockFactory.get(158, 3)),
    ACACIA_SLAB(BlockFactory.get(158, 4)),
    DARK_OAK_SLAB(BlockFactory.get(158, 5)),

    STAINED_HARDENED_CLAY(BlockFactory.get(159, 0)),
    COLORED_TERRACOTTA(BlockFactory.get(159, 0)),

    WHITE_TERRACOTTA(BlockFactory.get(159, 0)),
    ORANGE_TERRACOTTA(BlockFactory.get(159, 1)),
    MAGENTA_TERRACOTTA(BlockFactory.get(159, 2)),
    LIGHT_BLUE_TERRACOTTA(BlockFactory.get(159, 3)),
    YELLOW_TERRACOTTA(BlockFactory.get(159, 4)),
    LIME_TERRACOTTA(BlockFactory.get(159, 5)),
    PINK_TERRACOTTA(BlockFactory.get(159, 6)),
    GRAY_TERRACOTTA(BlockFactory.get(159, 7)),
    LIGHT_GRAY_TERRACOTTA(BlockFactory.get(159, 8)),
    CYAN_TERRACOTTA(BlockFactory.get(159, 9)),
    PURPLE_TERRACOTTA(BlockFactory.get(159, 10)),
    BLUE_TERRACOTTA(BlockFactory.get(159, 11)),
    BROWN_TERRACOTTA(BlockFactory.get(159, 12)),
    GREEN_TERRACOTTA(BlockFactory.get(159, 13)),
    RED_TERRACOTTA(BlockFactory.get(159, 14)),
    BLACK_TERRACOTTA(BlockFactory.get(159, 15)),

    STAINED_GLASS_PANE(BlockFactory.get(160, 0)),
    WHITE_STAINED_GLASS_PANE(BlockFactory.get(160, 0)),
    ORANGE_STAINED_GLASS_PANE(BlockFactory.get(160, 1)),
    MAGENTA_STAINED_GLASS_PANE(BlockFactory.get(160, 2)),
    LIGHT_BLUE_STAINED_GLASS_PANE(BlockFactory.get(160, 3)),
    YELLOW_STAINED_GLASS_PANE(BlockFactory.get(160, 4)),
    LIME_STAINED_GLASS_PANE(BlockFactory.get(160, 5)),
    PINK_STAINED_GLASS_PANE(BlockFactory.get(160, 6)),
    GRAY_STAINED_GLASS_PANE(BlockFactory.get(160, 7)),
    LIGHT_GRAY_STAINED_GLASS_PANE(BlockFactory.get(160, 8)),
    CYAN_STAINED_GLASS_PANE(BlockFactory.get(160, 9)),
    PURPLE_STAINED_GLASS_PANE(BlockFactory.get(160, 10)),
    BLUE_STAINED_GLASS_PANE(BlockFactory.get(160, 11)),
    BROWN_STAINED_GLASS_PANE(BlockFactory.get(160, 12)),
    GREEN_STAINED_GLASS_PANE(BlockFactory.get(160, 13)),
    RED_STAINED_GLASS_PANE(BlockFactory.get(160, 14)),
    BLACK_STAINED_GLASS_PANE(BlockFactory.get(160, 15)),

    LEAVES2(BlockFactory.get(161, 0)),
    ACACIA_LEAVES(BlockFactory.get(161, 0)),
    DARK_OAK_LEAVES(BlockFactory.get(161, 1)),

    LOG2(BlockFactory.get(162, 0)),
    ACACIA_LOG(BlockFactory.get(162, 0)),
    DARK_OAK_LOG(BlockFactory.get(162, 1)),

    ACACIA_STAIRS(BlockFactory.get(163, 0)),
    DARK_OAK_STAIRS(BlockFactory.get(164, 0)),
    SLIME_BLOCK(BlockFactory.get(165, 0)),
    GLOW_STICK(BlockFactory.get(166, 0)),
    IRON_TRAPDOOR(BlockFactory.get(167, 0)),

    PRISMARINE(BlockFactory.get(168, 0)),
    DARK_PRISMARINE(BlockFactory.get(168, 1)),
    PRISMARINE_BRICKS(BlockFactory.get(168, 2)),

    SEA_LANTERN(BlockFactory.get(169, 0)),

    HAY_BLOCK(BlockFactory.get(170, 0)),
    HAY_BALE(BlockFactory.get(170, 0)),

    CARPET(BlockFactory.get(171, 0)),
    WHITE_CARPET(BlockFactory.get(171, 0)),
    ORANGE_CARPET(BlockFactory.get(171, 1)),
    MAGENTA_CARPET(BlockFactory.get(171, 2)),
    LIGHT_BLUE_CARPET(BlockFactory.get(171, 3)),
    YELLOW_CARPET(BlockFactory.get(171, 4)),
    LIME_CARPET(BlockFactory.get(171, 5)),
    PINK_CARPET(BlockFactory.get(171, 6)),
    GRAY_CARPET(BlockFactory.get(171, 7)),
    LIGHT_GRAY_CARPET(BlockFactory.get(171, 8)),
    CYAN_CARPET(BlockFactory.get(171, 9)),
    PURPLE_CARPET(BlockFactory.get(171, 10)),
    BLUE_CARPET(BlockFactory.get(171, 11)),
    BROWN_CARPET(BlockFactory.get(171, 12)),
    GREEN_CARPET(BlockFactory.get(171, 13)),
    RED_CARPET(BlockFactory.get(171, 14)),
    BLACK_CARPET(BlockFactory.get(171, 15)),

    HARDENED_CLAY(BlockFactory.get(172, 0)),

    COAL_BLOCK(BlockFactory.get(173, 0)),
    BLOCK_OF_COAL(BlockFactory.get(173, 0)),

    PACKED_ICE(BlockFactory.get(174, 0)),

    DOUBLE_PLANT(BlockFactory.get(175, 0)),
    SUNFLOWER(BlockFactory.get(175, 0)),
    LILAC(BlockFactory.get(175, 1)),
    DOUBLE_TALLGRASS(BlockFactory.get(175, 2)),
    LARGE_FERN(BlockFactory.get(175, 3)),
    ROSE_BUSH(BlockFactory.get(175, 4)),
    PEONY(BlockFactory.get(175, 5)),

    STANDING_BANNER(BlockFactory.get(176, 0)),
    WALL_BANNER(BlockFactory.get(177, 2)),

    INVERTED_DAYLIGHT_DETECTOR(BlockFactory.get(178, 0)),

    RED_SANDSTONE(BlockFactory.get(179, 0)),
    CHISELED_RED_SANDSTONE(BlockFactory.get(179, 1)),
    CUT_RED_SANDSTONE(BlockFactory.get(179, 2)),
    SMOOTH_RED_SANDSTONE(BlockFactory.get(179, 3)),

    RED_SANDSTONE_STAIRS(BlockFactory.get(180, 0)),
    DOUBLE_RED_SANDSTONE(BlockFactory.get(181, 0)),

    STONE_SLAB2(BlockFactory.get(182, 0)),
    RED_SANDSTONE_SLAB(BlockFactory.get(182, 0)),
    PURPUR_SLAB(BlockFactory.get(182, 1)),
    PRISMARINE_SLAB(BlockFactory.get(182, 2)),
    DARK_PRISMARINE_SLAB(BlockFactory.get(182, 3)),
    PRISMARINE_BRICKS_SLAB(BlockFactory.get(182, 4)),
    MOSSY_COBBLESTONE_SLAB(BlockFactory.get(182, 5)),
    SMOOTH_SANDSTONE_SLAB(BlockFactory.get(182, 6)),
    RED_NETHER_BRICK_SLAB(BlockFactory.get(182, 7)),

    SPRUCE_FENCE_GATE(BlockFactory.get(183, 0)),
    BIRCH_FENCE_GATE(BlockFactory.get(184, 0)),
    JUNGLE_FENCE_GATE(BlockFactory.get(185, 0)),
    DARK_OAK_FENCE_GATE(BlockFactory.get(186, 0)),
    ACACIA_FENCE_GATE(BlockFactory.get(187, 0)),
    REPEATING_COMMAND_BLOCK(BlockFactory.get(188, 0)),
    CHAIN_COMMAND_BLOCK(BlockFactory.get(189, 0)),

    HARDENED_GLASS_PANE(BlockFactory.get(190, 0)),
    WHITE_HARDENED_GLASS_PANE(BlockFactory.get(190, 0)),
    ORANGE_HARDENED_GLASS_PANE(BlockFactory.get(190, 1)),
    MAGENTA_HARDENED_GLASS_PANE(BlockFactory.get(190, 2)),
    LIGHT_BLUE_HARDENED_GLASS_PANE(BlockFactory.get(190, 3)),
    YELLOW_HARDENED_GLASS_PANE(BlockFactory.get(190, 4)),
    LIME_HARDENED_GLASS_PANE(BlockFactory.get(190, 5)),
    PINK_HARDENED_GLASS_PANE(BlockFactory.get(190, 6)),
    GRAY_HARDENED_GLASS_PANE(BlockFactory.get(190, 7)),
    LIGHT_GRAY_HARDENED_GLASS_PANE(BlockFactory.get(190, 8)),
    CYAN_HARDENED_GLASS_PANE(BlockFactory.get(190, 9)),
    PURPLE_HARDENED_GLASS_PANE(BlockFactory.get(190, 10)),
    BLUE_HARDENED_GLASS_PANE(BlockFactory.get(190, 11)),
    BROWN_HARDENED_GLASS_PANE(BlockFactory.get(190, 12)),
    GREEN_HARDENED_GLASS_PANE(BlockFactory.get(190, 13)),
    RED_HARDENED_GLASS_PANE(BlockFactory.get(190, 14)),
    BLACK_HARDENED_GLASS_PANE(BlockFactory.get(190, 15)),

    HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 0)),
    WHITE_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 0)),
    ORANGE_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 1)),
    MAGENTA_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 2)),
    LIGHT_BLUE_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 3)),
    YELLOW_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 4)),
    LIME_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 5)),
    PINK_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 6)),
    GRAY_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 7)),
    LIGHT_GRAY_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 8)),
    CYAN_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 9)),
    PURPLE_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 10)),
    BLUE_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 11)),
    BROWN_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 12)),
    GREEN_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 13)),
    RED_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 14)),
    BLACK_HARDENED_STAINED_GLASS_PANE(BlockFactory.get(191, 15)),

    HEAD_BLOCK(BlockFactory.get(192, 0)),

    SPRUCE_DOOR(BlockFactory.get(193, 0)),
    BIRCH_DOOR(BlockFactory.get(194, 0)),
    JUNGLE_DOOR(BlockFactory.get(195, 0)),
    ACACIA_DOOR(BlockFactory.get(196, 0)),
    DARK_OAK_DOOR(BlockFactory.get(197, 0)),
    GRASS_PATH(BlockFactory.get(198, 0)),
    ITEM_FRAME(BlockFactory.get(199, 0)),

    CHORUS_FLOWER(BlockFactory.get(200, 0)),
    PURPUR_BLOCK(BlockFactory.get(201, 0)),
    CHISELED_PURPUR(BlockFactory.get(201, 2)),
    PURPUR_PILLAR_UP_DOWN(BlockFactory.get(201, 2)),
    SMOOTH_PURPUR(BlockFactory.get(201, 3)),
    PURPUR_PILLAR_EAST_WEST(BlockFactory.get(201, 6)),
    PURPUR_PILLAR_NORTH_SOUTH(BlockFactory.get(201, 10)),

    RED_TORCH(BlockFactory.get(202, 5)),
    GREEN_TORCH(BlockFactory.get(202, 13)),
    PURPUR_STAIRS(BlockFactory.get(203, 0)),
    BLUE_TORCH(BlockFactory.get(204, 5)),
    PURPLE_TORCH(BlockFactory.get(204, 13)),

    UNDYED_SHULKER_BOX(BlockFactory.get(205, 0)),
    WHITE_UNDYED_SHULKER_BOX(BlockFactory.get(205, 0)),
    ORANGE_UNDYED_SHULKER_BOX(BlockFactory.get(205, 1)),
    MAGENTA_UNDYED_SHULKER_BOX(BlockFactory.get(205, 2)),
    LIGHT_BLUE_UNDYED_SHULKER_BOX(BlockFactory.get(205, 3)),
    YELLOW_UNDYED_SHULKER_BOX(BlockFactory.get(205, 4)),
    LIME_UNDYED_SHULKER_BOX(BlockFactory.get(205, 5)),
    PINK_UNDYED_SHULKER_BOX(BlockFactory.get(205, 6)),
    GRAY_UNDYED_SHULKER_BOX(BlockFactory.get(205, 7)),
    LIGHT_GRAY_UNDYED_SHULKER_BOX(BlockFactory.get(205, 8)),
    CYAN_UNDYED_SHULKER_BOX(BlockFactory.get(205, 9)),
    PURPLE_UNDYED_SHULKER_BOX(BlockFactory.get(205, 10)),
    BLUE_UNDYED_SHULKER_BOX(BlockFactory.get(205, 11)),
    BROWN_UNDYED_SHULKER_BOX(BlockFactory.get(205, 12)),
    GREEN_UNDYED_SHULKER_BOX(BlockFactory.get(205, 13)),
    RED_UNDYED_SHULKER_BOX(BlockFactory.get(205, 14)),
    BLACK_UNDYED_SHULKER_BOX(BlockFactory.get(205, 15)),

    END_STONE_BRICKS(BlockFactory.get(206, 0)),
    FROSTED_ICE(BlockFactory.get(207, 0)),
    END_ROD(BlockFactory.get(208, 0)),
    END_GATEWAY(BlockFactory.get(209, 0)),

    ALLOW(BlockFactory.get(210, 0)),
    DENY(BlockFactory.get(211, 0)),
    BORDER(BlockFactory.get(212, 0)),

    MAGMA_BLOCK(BlockFactory.get(213, 0)),
    NETHER_WART_BLOCK(BlockFactory.get(214, 0)),
    RED_NETHER_BRICK(BlockFactory.get(215, 0)),
    BONE_BLOCK(BlockFactory.get(216, 0)),
    STRUCTURE_VOID(BlockFactory.get(217, 0)),

    SHULKER_BOX(BlockFactory.get(218, 0)),
    WHITE_SHULKER_BOX(BlockFactory.get(218, 0)),
    ORANGE_SHULKER_BOX(BlockFactory.get(218, 1)),
    MAGENTA_SHULKER_BOX(BlockFactory.get(218, 2)),
    LIGHT_BLUE_SHULKER_BOX(BlockFactory.get(218, 3)),
    YELLOW_SHULKER_BOX(BlockFactory.get(218, 4)),
    LIME_SHULKER_BOX(BlockFactory.get(218, 5)),
    PINK_SHULKER_BOX(BlockFactory.get(218, 6)),
    GRAY_SHULKER_BOX(BlockFactory.get(218, 7)),
    LIGHT_GRAY_SHULKER_BOX(BlockFactory.get(218, 8)),
    CYAN_SHULKER_BOX(BlockFactory.get(218, 9)),
    PURPLE_SHULKER_BOX(BlockFactory.get(218, 10)),
    BLUE_SHULKER_BOX(BlockFactory.get(218, 11)),
    BROWN_SHULKER_BOX(BlockFactory.get(218, 12)),
    GREEN_SHULKER_BOX(BlockFactory.get(218, 13)),
    RED_SHULKER_BOX(BlockFactory.get(218, 14)),
    BLACK_SHULKER_BOX(BlockFactory.get(218, 15)),

    PURPLE_GLAZED_TERRACOTTA(BlockFactory.get(219, 2)),
    WHITE_GLAZED_TERRACOTTA(BlockFactory.get(220, 2)),
    ORANGE_GLAZED_TERRACOTTA(BlockFactory.get(221, 2)),
    MAGENTA_GLAZED_TERRACOTTA(BlockFactory.get(222, 2)),
    LIGHT_BLUE_GLAZED_TERRACOTTA(BlockFactory.get(223, 2)),
    YELLOW_GLAZED_TERRACOTTA(BlockFactory.get(224, 2)),
    LIME_GLAZED_TERRACOTTA(BlockFactory.get(225, 2)),
    PINK_GLAZED_TERRACOTTA(BlockFactory.get(226, 2)),
    GRAY_GLAZED_TERRACOTTA(BlockFactory.get(227, 2)),
    LIGHT_GRAY_GLAZED_TERRACOTTA(BlockFactory.get(228, 2)),
    CYAN_GLAZED_TERRACOTTA(BlockFactory.get(229, 2)),
    CHALKBOARD(BlockFactory.get(230, 0)),
    BLUE_GLAZED_TERRACOTTA(BlockFactory.get(231, 2)),
    BROWN_GLAZED_TERRACOTTA(BlockFactory.get(232, 2)),
    GREEN_GLAZED_TERRACOTTA(BlockFactory.get(233, 2)),
    RED_GLAZED_TERRACOTTA(BlockFactory.get(234, 2)),
    BLACK_GLAZED_TERRACOTTA(BlockFactory.get(235, 2)),

    CONCRETE(BlockFactory.get(236, 0)),
    WHITE_CONCRETE(BlockFactory.get(236, 0)),
    ORANGE_CONCRETE(BlockFactory.get(236, 1)),
    MAGENTA_CONCRETE(BlockFactory.get(236, 2)),
    LIGHT_BLUE_CONCRETE(BlockFactory.get(236, 3)),
    YELLOW_CONCRETE(BlockFactory.get(236, 4)),
    LIME_CONCRETE(BlockFactory.get(236, 5)),
    PINK_CONCRETE(BlockFactory.get(236, 6)),
    GRAY_CONCRETE(BlockFactory.get(236, 7)),
    LIGHT_GRAY_CONCRETE(BlockFactory.get(236, 8)),
    CYAN_CONCRETE(BlockFactory.get(236, 9)),
    PURPLE_CONCRETE(BlockFactory.get(236, 10)),
    BLUE_CONCRETE(BlockFactory.get(236, 11)),
    BROWN_CONCRETE(BlockFactory.get(236, 12)),
    GREEN_CONCRETE(BlockFactory.get(236, 13)),
    RED_CONCRETE(BlockFactory.get(236, 14)),
    BLACK_CONCRETE(BlockFactory.get(236, 15)),

    CONCRETE_POWDER(BlockFactory.get(237, 0)),
    WHITE_CONCRETE_POWDER(BlockFactory.get(237, 0)),
    ORANGE_CONCRETE_POWDER(BlockFactory.get(237, 1)),
    MAGENTA_CONCRETE_POWDER(BlockFactory.get(237, 2)),
    LIGHT_BLUE_CONCRETE_POWDER(BlockFactory.get(237, 3)),
    YELLOW_CONCRETE_POWDER(BlockFactory.get(237, 4)),
    LIME_CONCRETE_POWDER(BlockFactory.get(237, 5)),
    PINK_CONCRETE_POWDER(BlockFactory.get(237, 6)),
    GRAY_CONCRETE_POWDER(BlockFactory.get(237, 7)),
    LIGHT_GRAY_CONCRETE_POWDER(BlockFactory.get(237, 8)),
    CYAN_CONCRETE_POWDER(BlockFactory.get(237, 9)),
    PURPLE_CONCRETE_POWDER(BlockFactory.get(237, 10)),
    BLUE_CONCRETE_POWDER(BlockFactory.get(237, 11)),
    BROWN_CONCRETE_POWDER(BlockFactory.get(237, 12)),
    GREEN_CONCRETE_POWDER(BlockFactory.get(237, 13)),
    RED_CONCRETE_POWDER(BlockFactory.get(237, 14)),
    BLACK_CONCRETE_POWDER(BlockFactory.get(237, 15)),

    CHEMISTRY_TABLE(BlockFactory.get(238, 0)),
    COMPOUND_CREATOR(BlockFactory.get(238, 0)),
    MATERIAL_REDUCER(BlockFactory.get(238, 4)),
    ELEMENT_CONSTRUCTOR(BlockFactory.get(238, 8)),
    LAB_TABLE(BlockFactory.get(238, 12)),

    UNDERWATER_TORCH(BlockFactory.get(239, 5)),
    CHORUS_PLANT(BlockFactory.get(240, 0)),

    STAINED_GLASS(BlockFactory.get(241, 0)),
    WHITE_STAINED_GLASS(BlockFactory.get(241, 0)),
    ORANGE_STAINED_GLASS(BlockFactory.get(241, 1)),
    MAGENTA_STAINED_GLASS(BlockFactory.get(241, 2)),
    LIGHT_BLUE_STAINED_GLASS(BlockFactory.get(241, 3)),
    YELLOW_STAINED_GLASS(BlockFactory.get(241, 4)),
    LIME_STAINED_GLASS(BlockFactory.get(241, 5)),
    PINK_STAINED_GLASS(BlockFactory.get(241, 6)),
    GRAY_STAINED_GLASS(BlockFactory.get(241, 7)),
    LIGHT_GRAY_STAINED_GLASS(BlockFactory.get(241, 8)),
    CYAN_STAINED_GLASS(BlockFactory.get(241, 9)),
    PURPLE_STAINED_GLASS(BlockFactory.get(241, 10)),
    BLUE_STAINED_GLASS(BlockFactory.get(241, 11)),
    BROWN_STAINED_GLASS(BlockFactory.get(241, 12)),
    GREEN_STAINED_GLASS(BlockFactory.get(241, 13)),
    RED_STAINED_GLASS(BlockFactory.get(241, 14)),
    BLACK_STAINED_GLASS(BlockFactory.get(241, 15)),

    PODZOL(BlockFactory.get(243, 0)),
    BEETROOTS(BlockFactory.get(244, 0)),
    STONECUTTER(BlockFactory.get(245, 0)),
    GLOWING_OBSIDIAN(BlockFactory.get(246, 0)),
    NETHER_REACTOR_CORE(BlockFactory.get(247, 0)),
    INFO_UPDATE(BlockFactory.get(248, 0)),
    INFO_UPDATE2(BlockFactory.get(249, 0)),

    MOVING_BLOCK(BlockFactory.get(250, 0)),
    MOVING_PISTON(BlockFactory.get(250, 0)),

    OBSERVER(BlockFactory.get(251, 0)),

    STRUCTURE_BLOCK(BlockFactory.get(252, 0)),
    STRUCTURE_BLOCK_DATA(BlockFactory.get(252, 0)),
    STRUCTURE_BLOCK_SAVE(BlockFactory.get(252, 1)),
    STRUCTURE_BLOCK_LOAD(BlockFactory.get(252, 2)),
    STRUCTURE_BLOCK_CORNER(BlockFactory.get(252, 3)),
    STRUCTURE_BLOCK_INVALID(BlockFactory.get(252, 4)),
    STRUCTURE_BLOCK_EXPORT(BlockFactory.get(252, 5)),

    HARDENED_GLASS(BlockFactory.get(253, 0)),
    WHITE_HARDENED_GLASS(BlockFactory.get(253, 0)),
    ORANGE_HARDENED_GLASS(BlockFactory.get(253, 1)),
    MAGENTA_HARDENED_GLASS(BlockFactory.get(253, 2)),
    LIGHT_BLUE_HARDENED_GLASS(BlockFactory.get(253, 3)),
    YELLOW_HARDENED_GLASS(BlockFactory.get(253, 4)),
    LIME_HARDENED_GLASS(BlockFactory.get(253, 5)),
    PINK_HARDENED_GLASS(BlockFactory.get(253, 6)),
    GRAY_HARDENED_GLASS(BlockFactory.get(253, 7)),
    LIGHT_GRAY_HARDENED_GLASS(BlockFactory.get(253, 8)),
    CYAN_HARDENED_GLASS(BlockFactory.get(253, 9)),
    PURPLE_HARDENED_GLASS(BlockFactory.get(253, 10)),
    BLUE_HARDENED_GLASS(BlockFactory.get(253, 11)),
    BROWN_HARDENED_GLASS(BlockFactory.get(253, 12)),
    GREEN_HARDENED_GLASS(BlockFactory.get(253, 13)),
    RED_HARDENED_GLASS(BlockFactory.get(253, 14)),
    BLACK_HARDENED_GLASS(BlockFactory.get(253, 15)),

    HARDENED_STAINED_GLASS(BlockFactory.get(254, 0)),
    WHITE_HARDENED_STAINED_GLASS(BlockFactory.get(254, 0)),
    ORANGE_HARDENED_STAINED_GLASS(BlockFactory.get(254, 1)),
    MAGENTA_HARDENED_STAINED_GLASS(BlockFactory.get(254, 2)),
    LIGHT_BLUE_HARDENED_STAINED_GLASS(BlockFactory.get(254, 3)),
    YELLOW_HARDENED_STAINED_GLASS(BlockFactory.get(254, 4)),
    LIME_HARDENED_STAINED_GLASS(BlockFactory.get(254, 5)),
    PINK_HARDENED_STAINED_GLASS(BlockFactory.get(254, 6)),
    GRAY_HARDENED_STAINED_GLASS(BlockFactory.get(254, 7)),
    LIGHT_GRAY_HARDENED_STAINED_GLASS(BlockFactory.get(254, 8)),
    CYAN_HARDENED_STAINED_GLASS(BlockFactory.get(254, 9)),
    PURPLE_HARDENED_STAINED_GLASS(BlockFactory.get(254, 10)),
    BLUE_HARDENED_STAINED_GLASS(BlockFactory.get(254, 11)),
    BROWN_HARDENED_STAINED_GLASS(BlockFactory.get(254, 12)),
    GREEN_HARDENED_STAINED_GLASS(BlockFactory.get(254, 13)),
    RED_HARDENED_STAINED_GLASS(BlockFactory.get(254, 14)),
    BLACK_HARDENED_STAINED_GLASS(BlockFactory.get(254, 15)),

    RESERVED6(BlockFactory.get(255, 0)),

    PRISMARINE_STAIRS(BlockFactory.get(257, 0)),
    DARK_PRISMARINE_STAIRS(BlockFactory.get(258, 0)),
    PRISMARINE_BRICKS_STAIRS(BlockFactory.get(259, 0)),

    STRIPPED_SPRUCE_LOG(BlockFactory.get(260, 0)),
    STRIPPED_BIRCH_LOG(BlockFactory.get(261, 0)),
    STRIPPED_JUNGLE_LOG(BlockFactory.get(262, 0)),
    STRIPPED_ACACIA_LOG(BlockFactory.get(263, 0)),
    STRIPPED_DARK_OAK_LOG(BlockFactory.get(264, 0)),
    STRIPPED_OAK_LOG(BlockFactory.get(265, 0)),

    BLUE_ICE(BlockFactory.get(266, 0)),
    ELEMENT_1(BlockFactory.get(267, 0)),
    ELEMENT_HYDROGEN(BlockFactory.get(267, 0)),
    ELEMENT_2(BlockFactory.get(268, 0)),
    ELEMENT_HELIUM(BlockFactory.get(268, 0)),
    ELEMENT_3(BlockFactory.get(269, 0)),
    ELEMENT_LITHIUM(BlockFactory.get(269, 0)),
    ELEMENT_4(BlockFactory.get(270, 0)),
    ELEMENT_BERYLLIUM(BlockFactory.get(270, 0)),
    ELEMENT_5(BlockFactory.get(271, 0)),
    ELEMENT_BORON(BlockFactory.get(271, 0)),
    ELEMENT_6(BlockFactory.get(272, 0)),
    ELEMENT_CARBON(BlockFactory.get(272, 0)),
    ELEMENT_7(BlockFactory.get(273, 0)),
    ELEMENT_NITROGEN(BlockFactory.get(273, 0)),
    ELEMENT_8(BlockFactory.get(274, 0)),
    ELEMENT_OXYGEN(BlockFactory.get(274, 0)),
    ELEMENT_9(BlockFactory.get(275, 0)),
    ELEMENT_FLUORINE(BlockFactory.get(275, 0)),
    ELEMENT_10(BlockFactory.get(276, 0)),
    ELEMENT_NEON(BlockFactory.get(276, 0)),
    ELEMENT_11(BlockFactory.get(277, 0)),
    ELEMENT_SODIUM(BlockFactory.get(277, 0)),
    ELEMENT_12(BlockFactory.get(278, 0)),
    ELEMENT_MAGNESIUM(BlockFactory.get(278, 0)),
    ELEMENT_13(BlockFactory.get(279, 0)),
    ELEMENT_ALUMINUM(BlockFactory.get(279, 0)),
    ELEMENT_14(BlockFactory.get(280, 0)),
    ELEMENT_SILICON(BlockFactory.get(280, 0)),
    ELEMENT_15(BlockFactory.get(281, 0)),
    ELEMENT_PHOSPHORUS(BlockFactory.get(281, 0)),
    ELEMENT_16(BlockFactory.get(282, 0)),
    ELEMENT_SULFUR(BlockFactory.get(282, 0)),
    ELEMENT_17(BlockFactory.get(283, 0)),
    ELEMENT_CHLORINE(BlockFactory.get(283, 0)),
    ELEMENT_18(BlockFactory.get(284, 0)),
    ELEMENT_ARGON(BlockFactory.get(284, 0)),
    ELEMENT_19(BlockFactory.get(285, 0)),
    ELEMENT_POTASSIUM(BlockFactory.get(285, 0)),
    ELEMENT_20(BlockFactory.get(286, 0)),
    ELEMENT_CALCIUM(BlockFactory.get(286, 0)),
    ELEMENT_21(BlockFactory.get(287, 0)),
    ELEMENT_SCANDIUM(BlockFactory.get(287, 0)),
    ELEMENT_22(BlockFactory.get(288, 0)),
    ELEMENT_TITANIUM(BlockFactory.get(288, 0)),
    ELEMENT_23(BlockFactory.get(289, 0)),
    ELEMENT_VANADIUM(BlockFactory.get(289, 0)),
    ELEMENT_24(BlockFactory.get(290, 0)),
    ELEMENT_CHROMIUM(BlockFactory.get(290, 0)),
    ELEMENT_25(BlockFactory.get(291, 0)),
    ELEMENT_MANGANESE(BlockFactory.get(291, 0)),
    ELEMENT_26(BlockFactory.get(292, 0)),
    ELEMENT_IRON(BlockFactory.get(292, 0)),
    ELEMENT_27(BlockFactory.get(293, 0)),
    ELEMENT_COBALT(BlockFactory.get(293, 0)),
    ELEMENT_28(BlockFactory.get(294, 0)),
    ELEMENT_NICKEL(BlockFactory.get(294, 0)),
    ELEMENT_29(BlockFactory.get(295, 0)),
    ELEMENT_COPPER(BlockFactory.get(295, 0)),
    ELEMENT_30(BlockFactory.get(296, 0)),
    ELEMENT_ZINC(BlockFactory.get(296, 0)),
    ELEMENT_31(BlockFactory.get(297, 0)),
    ELEMENT_GALLIUM(BlockFactory.get(297, 0)),
    ELEMENT_32(BlockFactory.get(298, 0)),
    ELEMENT_GERMANIUM(BlockFactory.get(298, 0)),
    ELEMENT_33(BlockFactory.get(299, 0)),
    ELEMENT_ARSENIC(BlockFactory.get(299, 0)),
    ELEMENT_34(BlockFactory.get(300, 0)),
    ELEMENT_SELENIUM(BlockFactory.get(300, 0)),
    ELEMENT_35(BlockFactory.get(301, 0)),
    ELEMENT_BROMINE(BlockFactory.get(301, 0)),
    ELEMENT_36(BlockFactory.get(302, 0)),
    ELEMENT_KRYPTON(BlockFactory.get(302, 0)),
    ELEMENT_37(BlockFactory.get(303, 0)),
    ELEMENT_RUBIDIUM(BlockFactory.get(303, 0)),
    ELEMENT_38(BlockFactory.get(304, 0)),
    ELEMENT_STRONTIUM(BlockFactory.get(304, 0)),
    ELEMENT_39(BlockFactory.get(305, 0)),
    ELEMENT_YTTRIUM(BlockFactory.get(305, 0)),
    ELEMENT_40(BlockFactory.get(306, 0)),
    ELEMENT_ZIRCONIUM(BlockFactory.get(306, 0)),
    ELEMENT_41(BlockFactory.get(307, 0)),
    ELEMENT_NIOBIUM(BlockFactory.get(307, 0)),
    ELEMENT_42(BlockFactory.get(308, 0)),
    ELEMENT_MOLYBDENUM(BlockFactory.get(308, 0)),
    ELEMENT_43(BlockFactory.get(309, 0)),
    ELEMENT_TECHNETIUM(BlockFactory.get(309, 0)),
    ELEMENT_44(BlockFactory.get(310, 0)),
    ELEMENT_RUTHENIUM(BlockFactory.get(310, 0)),
    ELEMENT_45(BlockFactory.get(311, 0)),
    ELEMENT_RHODIUM(BlockFactory.get(311, 0)),
    ELEMENT_46(BlockFactory.get(312, 0)),
    ELEMENT_PALLADIUM(BlockFactory.get(312, 0)),
    ELEMENT_47(BlockFactory.get(313, 0)),
    ELEMENT_SILVER(BlockFactory.get(313, 0)),
    ELEMENT_48(BlockFactory.get(314, 0)),
    ELEMENT_CADMIUM(BlockFactory.get(314, 0)),
    ELEMENT_49(BlockFactory.get(315, 0)),
    ELEMENT_INDIUM(BlockFactory.get(315, 0)),
    ELEMENT_50(BlockFactory.get(316, 0)),
    ELEMENT_TIN(BlockFactory.get(316, 0)),
    ELEMENT_51(BlockFactory.get(317, 0)),
    ELEMENT_ANTIMONY(BlockFactory.get(317, 0)),
    ELEMENT_52(BlockFactory.get(318, 0)),
    ELEMENT_TELLURIUM(BlockFactory.get(318, 0)),
    ELEMENT_53(BlockFactory.get(319, 0)),
    ELEMENT_IODINE(BlockFactory.get(319, 0)),
    ELEMENT_54(BlockFactory.get(320, 0)),
    ELEMENT_XENON(BlockFactory.get(320, 0)),
    ELEMENT_55(BlockFactory.get(321, 0)),
    ELEMENT_CESIUM(BlockFactory.get(321, 0)),
    ELEMENT_56(BlockFactory.get(322, 0)),
    ELEMENT_BARIUM(BlockFactory.get(322, 0)),
    ELEMENT_57(BlockFactory.get(323, 0)),
    ELEMENT_LANTHANUM(BlockFactory.get(323, 0)),
    ELEMENT_58(BlockFactory.get(324, 0)),
    ELEMENT_CERIUM(BlockFactory.get(324, 0)),
    ELEMENT_59(BlockFactory.get(325, 0)),
    ELEMENT_PRASEODYMIUM(BlockFactory.get(325, 0)),
    ELEMENT_60(BlockFactory.get(326, 0)),
    ELEMENT_NEODYMIUM(BlockFactory.get(326, 0)),
    ELEMENT_61(BlockFactory.get(327, 0)),
    ELEMENT_PROMETHIUM(BlockFactory.get(327, 0)),
    ELEMENT_62(BlockFactory.get(328, 0)),
    ELEMENT_SAMARIUM(BlockFactory.get(328, 0)),
    ELEMENT_63(BlockFactory.get(329, 0)),
    ELEMENT_EUROPIUM(BlockFactory.get(329, 0)),
    ELEMENT_64(BlockFactory.get(330, 0)),
    ELEMENT_GADOLINIUM(BlockFactory.get(330, 0)),
    ELEMENT_65(BlockFactory.get(331, 0)),
    ELEMENT_TERBIUM(BlockFactory.get(331, 0)),
    ELEMENT_66(BlockFactory.get(332, 0)),
    ELEMENT_DYSPROSIUM(BlockFactory.get(332, 0)),
    ELEMENT_67(BlockFactory.get(333, 0)),
    ELEMENT_HOLMIUM(BlockFactory.get(333, 0)),
    ELEMENT_68(BlockFactory.get(334, 0)),
    ELEMENT_ERBIUM(BlockFactory.get(334, 0)),
    ELEMENT_69(BlockFactory.get(335, 0)),
    ELEMENT_THULIUM(BlockFactory.get(335, 0)),
    ELEMENT_70(BlockFactory.get(336, 0)),
    ELEMENT_YTTERBIUM(BlockFactory.get(336, 0)),
    ELEMENT_71(BlockFactory.get(337, 0)),
    ELEMENT_LUTETIUM(BlockFactory.get(337, 0)),
    ELEMENT_72(BlockFactory.get(338, 0)),
    ELEMENT_HAFNIUM(BlockFactory.get(338, 0)),
    ELEMENT_73(BlockFactory.get(339, 0)),
    ELEMENT_TANTALUM(BlockFactory.get(339, 0)),
    ELEMENT_74(BlockFactory.get(340, 0)),
    ELEMENT_TUNGSTEN(BlockFactory.get(340, 0)),
    ELEMENT_75(BlockFactory.get(341, 0)),
    ELEMENT_RHENIUM(BlockFactory.get(341, 0)),
    ELEMENT_76(BlockFactory.get(342, 0)),
    ELEMENT_OSMIUM(BlockFactory.get(342, 0)),
    ELEMENT_77(BlockFactory.get(343, 0)),
    ELEMENT_IRIDIUM(BlockFactory.get(343, 0)),
    ELEMENT_78(BlockFactory.get(344, 0)),
    ELEMENT_PLATINUM(BlockFactory.get(344, 0)),
    ELEMENT_79(BlockFactory.get(345, 0)),
    ELEMENT_GOLD(BlockFactory.get(345, 0)),
    ELEMENT_80(BlockFactory.get(346, 0)),
    ELEMENT_MERCURY(BlockFactory.get(346, 0)),
    ELEMENT_81(BlockFactory.get(347, 0)),
    ELEMENT_THALLIUM(BlockFactory.get(347, 0)),
    ELEMENT_82(BlockFactory.get(348, 0)),
    ELEMENT_LEAD(BlockFactory.get(348, 0)),
    ELEMENT_83(BlockFactory.get(349, 0)),
    ELEMENT_BISMUTH(BlockFactory.get(349, 0)),
    ELEMENT_84(BlockFactory.get(350, 0)),
    ELEMENT_POLONIUM(BlockFactory.get(350, 0)),
    ELEMENT_85(BlockFactory.get(351, 0)),
    ELEMENT_ASTATINE(BlockFactory.get(351, 0)),
    ELEMENT_86(BlockFactory.get(352, 0)),
    ELEMENT_RADON(BlockFactory.get(352, 0)),
    ELEMENT_87(BlockFactory.get(353, 0)),
    ELEMENT_FRANCIUM(BlockFactory.get(353, 0)),
    ELEMENT_88(BlockFactory.get(354, 0)),
    ELEMENT_RADIUM(BlockFactory.get(354, 0)),
    ELEMENT_89(BlockFactory.get(355, 0)),
    ELEMENT_ACTINIUM(BlockFactory.get(355, 0)),
    ELEMENT_90(BlockFactory.get(356, 0)),
    ELEMENT_THORIUM(BlockFactory.get(356, 0)),
    ELEMENT_91(BlockFactory.get(357, 0)),
    ELEMENT_PROTACTINIUM(BlockFactory.get(357, 0)),
    ELEMENT_92(BlockFactory.get(358, 0)),
    ELEMENT_URANIUM(BlockFactory.get(358, 0)),
    ELEMENT_93(BlockFactory.get(359, 0)),
    ELEMENT_NEPTUNIUM(BlockFactory.get(359, 0)),
    ELEMENT_94(BlockFactory.get(360, 0)),
    ELEMENT_PLUTONIUM(BlockFactory.get(360, 0)),
    ELEMENT_95(BlockFactory.get(361, 0)),
    ELEMENT_AMERICIUM(BlockFactory.get(361, 0)),
    ELEMENT_96(BlockFactory.get(362, 0)),
    ELEMENT_CURIUM(BlockFactory.get(362, 0)),
    ELEMENT_97(BlockFactory.get(363, 0)),
    ELEMENT_BERKELIUM(BlockFactory.get(363, 0)),
    ELEMENT_98(BlockFactory.get(364, 0)),
    ELEMENT_CALIFORNIUM(BlockFactory.get(364, 0)),
    ELEMENT_99(BlockFactory.get(365, 0)),
    ELEMENT_EINSTEINIUM(BlockFactory.get(365, 0)),
    ELEMENT_100(BlockFactory.get(366, 0)),
    ELEMENT_FERMIUM(BlockFactory.get(366, 0)),
    ELEMENT_101(BlockFactory.get(367, 0)),
    ELEMENT_MENDELEVIUM(BlockFactory.get(367, 0)),
    ELEMENT_102(BlockFactory.get(368, 0)),
    ELEMENT_NOBELIUM(BlockFactory.get(368, 0)),
    ELEMENT_103(BlockFactory.get(369, 0)),
    ELEMENT_LAWRENCIUM(BlockFactory.get(369, 0)),
    ELEMENT_104(BlockFactory.get(370, 0)),
    ELEMENT_RUTHERFORDIUM(BlockFactory.get(370, 0)),
    ELEMENT_105(BlockFactory.get(371, 0)),
    ELEMENT_DUBNIUM(BlockFactory.get(371, 0)),
    ELEMENT_106(BlockFactory.get(372, 0)),
    ELEMENT_SEABORGIUM(BlockFactory.get(372, 0)),
    ELEMENT_107(BlockFactory.get(373, 0)),
    ELEMENT_BOHRIUM(BlockFactory.get(373, 0)),
    ELEMENT_108(BlockFactory.get(374, 0)),
    ELEMENT_HASSIUM(BlockFactory.get(374, 0)),
    ELEMENT_109(BlockFactory.get(375, 0)),
    ELEMENT_MEITNERIUM(BlockFactory.get(375, 0)),
    ELEMENT_110(BlockFactory.get(376, 0)),
    ELEMENT_DARMSTADTIUM(BlockFactory.get(376, 0)),
    ELEMENT_111(BlockFactory.get(377, 0)),
    ELEMENT_ROENTGENIUM(BlockFactory.get(377, 0)),
    ELEMENT_112(BlockFactory.get(378, 0)),
    ELEMENT_COPERNICIUM(BlockFactory.get(378, 0)),
    ELEMENT_113(BlockFactory.get(379, 0)),
    ELEMENT_NIHONIUM(BlockFactory.get(379, 0)),
    ELEMENT_114(BlockFactory.get(380, 0)),
    ELEMENT_FLEROVIUM(BlockFactory.get(380, 0)),
    ELEMENT_115(BlockFactory.get(381, 0)),
    ELEMENT_MOSCOVIUM(BlockFactory.get(381, 0)),
    ELEMENT_116(BlockFactory.get(382, 0)),
    ELEMENT_LIVERMORIUM(BlockFactory.get(382, 0)),
    ELEMENT_117(BlockFactory.get(383, 0)),
    ELEMENT_TENNESSINE(BlockFactory.get(383, 0)),
    ELEMENT_118(BlockFactory.get(384, 0)),
    ELEMENT_OGANESSON(BlockFactory.get(384, 0)),

    SEAGRASS(BlockFactory.get(385, 0)),

    CORAL(BlockFactory.get(386, 0)),
    TUBE_CORAL(BlockFactory.get(386, 0)),
    BRAIN_CORAL(BlockFactory.get(386, 1)),
    BUBBLE_CORAL(BlockFactory.get(386, 2)),
    FIRE_CORAL(BlockFactory.get(386, 3)),
    HORN_CORAL(BlockFactory.get(386, 4)),
    DEAD_TUBE_CORAL(BlockFactory.get(386, 8)),
    DEAD_BRAIN_CORAL(BlockFactory.get(386, 9)),
    DEAD_BUBBLE_CORAL(BlockFactory.get(386, 10)),
    DEAD_FIRE_CORAL(BlockFactory.get(386, 11)),
    DEAD_HORN_CORAL(BlockFactory.get(386, 12)),

    CORAL_BLOCK(BlockFactory.get(387, 0)),
    TUBE_CORAL_BLOCK(BlockFactory.get(387, 0)),
    BRAIN_CORAL_BLOCK(BlockFactory.get(387, 1)),
    BUBBLE_CORAL_BLOCK(BlockFactory.get(387, 2)),
    FIRE_CORAL_BLOCK(BlockFactory.get(387, 3)),
    HORN_CORAL_BLOCK(BlockFactory.get(387, 4)),
    DEAD_TUBE_CORAL_BLOCK(BlockFactory.get(387, 8)),
    DEAD_BRAIN_CORAL_BLOCK(BlockFactory.get(387, 9)),
    DEAD_BUBBLE_CORAL_BLOCK(BlockFactory.get(387, 10)),
    DEAD_FIRE_CORAL_BLOCK(BlockFactory.get(387, 11)),
    DEAD_HORN_CORAL_BLOCK(BlockFactory.get(387, 12)),

    CORAL_FAN(BlockFactory.get(388, 0)),
    TUBE_CORAL_FAN(BlockFactory.get(387, 0)),
    BRAIN_CORAL_FAN(BlockFactory.get(387, 1)),
    BUBBLE_CORAL_FAN(BlockFactory.get(387, 2)),
    FIRE_CORAL_FAN(BlockFactory.get(387, 3)),
    HORN_CORAL_FAN(BlockFactory.get(387, 4)),

    DEAD_CORAL_FAN(BlockFactory.get(389, 0)),
    DEAD_TUBE_CORAL_FAN(BlockFactory.get(389, 0)),
    DEAD_BRAIN_CORAL_FAN(BlockFactory.get(389, 1)),
    DEAD_BUBBLE_CORAL_FAN_(BlockFactory.get(389, 2)),
    DEAD_FIRE_CORAL_FAN(BlockFactory.get(389, 3)),
    DEAD_HORN_CORAL_FAN(BlockFactory.get(389, 4)),

    CORAL_WALL_FAN(BlockFactory.get(390, 0)),
    TUBE_CORAL_WALL_FAN(BlockFactory.get(390, 0)),
    BRAIN_CORAL_WALL_FAN(BlockFactory.get(390, 1)),
    DEAD_TUBE_CORAL_WALL_FAN(BlockFactory.get(390, 2)),
    DEAD_BRAIN_CORAL_WALL_FAN(BlockFactory.get(390, 3)),

    CORAL_WALL_FAN2(BlockFactory.get(391, 0)),
    BUBBLE_CORAL_WALL_FAN(BlockFactory.get(391, 0)),
    FIRE_CORAL_WALL_FAN(BlockFactory.get(391, 1)),
    DEAD_BUBBLE_CORAL_WALL_FAN(BlockFactory.get(391, 2)),
    DEAD_FIRE_CORAL_WALL_FAN(BlockFactory.get(391, 3)),

    CORAL_WALL_FAN3(BlockFactory.get(392, 0)),
    HORN_CORAL_WALL_FAN(BlockFactory.get(392, 0)),
    DEAD_HORN_CORAL_WALL_FAN(BlockFactory.get(392, 2)),

    KELP(BlockFactory.get(393, 0)),
    DRIED_KELP_BLOCK(BlockFactory.get(394, 0)),

    ACACIA_BUTTON(BlockFactory.get(395, 0)),
    BIRCH_BUTTON(BlockFactory.get(396, 0)),
    DARK_OAK_BUTTON(BlockFactory.get(397, 0)),
    JUNGLE_BUTTON(BlockFactory.get(398, 0)),
    SPRUCE_BUTTON(BlockFactory.get(399, 0)),

    ACACIA_TRAPDOOR(BlockFactory.get(400, 0)),
    BIRCH_TRAPDOOR(BlockFactory.get(401, 0)),
    DARK_OAK_TRAPDOOR(BlockFactory.get(402, 0)),
    JUNGLE_TRAPDOOR(BlockFactory.get(403, 0)),
    SPRUCE_TRAPDOOR(BlockFactory.get(404, 0)),

    ACACIA_PRESSURE_PLATE(BlockFactory.get(405, 0)),
    BIRCH_PRESSURE_PLATE(BlockFactory.get(406, 0)),
    DARK_OAK_PRESSURE_PLATE(BlockFactory.get(407, 0)),
    JUNGLE_PRESSURE_PLATE(BlockFactory.get(408, 0)),
    SPRUCE_PRESSURE_PLATE(BlockFactory.get(409, 0)),

    CARVED_PUMPKIN(BlockFactory.get(410, 0)),
    SEA_PICKLE(BlockFactory.get(411, 0)),
    CONDUIT(BlockFactory.get(412, 0)),
    SEE_TURTLE_EGG(BlockFactory.get(414, 0)),

    BUBBLE_COLUMN_DOWN(BlockFactory.get(415, 0)),
    BUBBLE_COLUMN_UP(BlockFactory.get(415, 1)),

    BARRIER(BlockFactory.get(416, 0)),

    STONE_SLAB3(BlockFactory.get(417, 0)),
    END_STONE_BRICK_SLAB(BlockFactory.get(417, 0)),
    SMOOTH_RED_SANDSTONE_SLAB(BlockFactory.get(417, 1)),
    POLISHED_ANDESITE_SLAB(BlockFactory.get(417, 2)),
    ANDESITE_SLAB(BlockFactory.get(417, 3)),
    DIORITE_SLAB(BlockFactory.get(417, 4)),
    POLISHED_DIORITE_SLAB(BlockFactory.get(417, 5)),
    GRANITE_SLAB(BlockFactory.get(417, 6)),
    POLISHED_GRANITE_SLAB(BlockFactory.get(417, 7)),

    BAMBOO(BlockFactory.get(418, 0)),
    BAMBOO_SAPLING(BlockFactory.get(419, 0)),
    SCAFFOLDING(BlockFactory.get(420, 0)),

    STONE_SLAB4(BlockFactory.get(421, 0)),
    MOSSY_STONE_BRICK_SLAB(BlockFactory.get(421, 0)),
    SMOOTH_QUARTZ_SLAB(BlockFactory.get(421, 1)),
    STONE_SLAB(BlockFactory.get(421, 2)),
    CUT_SANDSTONE_SLAB(BlockFactory.get(421, 3)),
    CUT_RED_SANDSTONE_SLAB(BlockFactory.get(421, 4)),

    DOUBLE_END_STONE_SLAB(BlockFactory.get(422, 0)),
    DOUBLE_MOSSY_STONE_SLAB(BlockFactory.get(423, 0)),

    GRANITE_STAIRS(BlockFactory.get(424, 0)),
    DIORITE_STAIRS(BlockFactory.get(425, 0)),
    ANDESITE_STAIRS(BlockFactory.get(426, 0)),
    POLISHED_GRANITE_STAIRS(BlockFactory.get(427, 0)),
    POLISHED_DIORITE_STAIRS(BlockFactory.get(428, 0)),
    POLISHED_ANDESITE_STAIRS(BlockFactory.get(429, 0)),
    MOSSY_STONE_BRICK_STAIRS(BlockFactory.get(430, 0)),
    SMOOTH_RED_SANDSTONE_STAIRS(BlockFactory.get(431, 0)),
    SMOOTH_SANDSTONE_STAIRS(BlockFactory.get(432, 0)),
    END_STONE_BRICK_STAIRS(BlockFactory.get(433, 0)),
    MOSSY_COBBLESTONE_STAIRS(BlockFactory.get(434, 0)),
    STONE_STAIRS(BlockFactory.get(435, 0)),

    SPRUCE_STANDING_SIGN(BlockFactory.get(436, 0)),
    SPRUCE_WALL_SIGN(BlockFactory.get(437, 2)),

    SMOOTH_STONE(BlockFactory.get(438, 0)),

    RED_NETHER_BRICK_STAIRS(BlockFactory.get(439, 0)),
    SMOOTH_QUARTZ_STAIRS(BlockFactory.get(440, 0)),

    BIRCH_STANDING_SIGN(BlockFactory.get(441, 0)),
    BIRCH_WALL_SIGN(BlockFactory.get(442, 2)),
    JUNGLE_STANDING_SIGN(BlockFactory.get(443, 0)),
    JUNGLE_WALL_SIGN(BlockFactory.get(444, 2)),
    ACACIA_STANDING_SIGN(BlockFactory.get(445, 0)),
    ACACIA_WALL_SIGN(BlockFactory.get(446, 2)),
    DARK_OAK_STANDING_SIGN(BlockFactory.get(447, 0)),
    DARK_OAK_WALL_SIGN(BlockFactory.get(448, 2)),

    LECTERN(BlockFactory.get(449, 0)),
    GRINDSTONE(BlockFactory.get(450, 0)),
    BLAST_FURNACE(BlockFactory.get(451, 0)),
    STONECUTTER_BLOCK(BlockFactory.get(452, 0)),
    SMOKER(BlockFactory.get(453, 0)),
    LIT_SMOKER(BlockFactory.get(454, 0)),
    CARTOGRAPHY_TABLE(BlockFactory.get(455, 0)),
    FLETCHING_TABLE(BlockFactory.get(456, 0)),
    SMITHING_TABLE(BlockFactory.get(457, 0)),
    BARREL(BlockFactory.get(458, 0)),
    LOOM(BlockFactory.get(459, 0)),
    BELL(BlockFactory.get(461, 0)),
    SWEET_BERRY_BUSH(BlockFactory.get(462, 0)),
    LANTERN(BlockFactory.get(463, 0)),
    CAMPFIRE(BlockFactory.get(464, 0)),
    LAVA_CAULDRON(BlockFactory.get(465, 0)),
    JIGSAW(BlockFactory.get(466, 0)),

    WOOD(BlockFactory.get(467, 0)),
    OAK_WOOD(BlockFactory.get(467, 0)),
    SPRUCE_WOOD(BlockFactory.get(467, 1)),
    BIRCH_WOOD(BlockFactory.get(467, 2)),
    JUNGLE_WOOD(BlockFactory.get(467, 3)),
    ACACIA_WOOD(BlockFactory.get(467, 4)),
    DARK_OAK_WOOD(BlockFactory.get(467, 5)),
    STRIPPED_OAK_WOOD(BlockFactory.get(467, 8)),
    STRIPPED_SPRUCE_WOOD(BlockFactory.get(467, 9)),
    STRIPPED_BIRCH_WOOD(BlockFactory.get(467, 10)),
    STRIPPED_JUNGLE_WOOD(BlockFactory.get(467, 11)),
    STRIPPED_ACACIA_WOOD(BlockFactory.get(467, 12)),
    STRIPPED_DARK_OAK_WOOD(BlockFactory.get(467, 13)),

    COMPOSTER(BlockFactory.get(468, 0)),
    LIT_BLAST_FURNACE(BlockFactory.get(469, 0)),
    LIGHT_BLOCK(BlockFactory.get(470, 0)),
    WITHER_ROSE(BlockFactory.get(471, 0)),
    STICKY_PISTON_HEAD(BlockFactory.get(472, 0)),

    BEE_NEST(BlockFactory.get(473, 0)),
    BEEHIVE(BlockFactory.get(474, 0)),
    HONEY_BLOCK(BlockFactory.get(475, 0)),
    HONEYCOMB_BLOCK(BlockFactory.get(476, 0)),

    LODESTONE(BlockFactory.get(477, 0)),

    CRIMSON_ROOTS(BlockFactory.get(478, 0)),
    WARPED_ROOTS(BlockFactory.get(479, 0)),
    CRIMSON_STEM(BlockFactory.get(480, 0)),
    WARPED_STEM(BlockFactory.get(481, 0)),
    WARPED_WART_BLOCK(BlockFactory.get(482, 0)),
    CRIMSON_FUNGUS(BlockFactory.get(483, 0)),
    WARPED_FUNGUS(BlockFactory.get(484, 0)),

    SHROOMLIGHT(BlockFactory.get(485, 0)),
    WEEPING_VINES(BlockFactory.get(486, 0)),

    CRIMSON_NYLIUM(BlockFactory.get(487, 0)),
    WARPED_NYLIUM(BlockFactory.get(488, 0)),

    BASALT(BlockFactory.get(489, 0)),
    POLISHED_BASALT(BlockFactory.get(490, 0)),

    SOUL_SOIL(BlockFactory.get(491, 0)),
    SOUL_FIRE(BlockFactory.get(492, 0)),

    NETHER_SPROUTS(BlockFactory.get(493, 0)),
    TARGET(BlockFactory.get(494, 0)),

    STRIPPED_CRIMSON_STEM(BlockFactory.get(495, 0)),
    STRIPPED_WARPED_STEM(BlockFactory.get(496, 0)),
    CRIMSON_PLANKS(BlockFactory.get(497, 0)),
    WARPED_PLANKS(BlockFactory.get(498, 0)),
    CRIMSON_DOOR(BlockFactory.get(499, 0)),
    WARPED_DOOR(BlockFactory.get(500, 0)),
    CRIMSON_TRAPDOOR(BlockFactory.get(501, 0)),
    WARPED_TRAPDOOR(BlockFactory.get(502, 0)),
    CRIMSON_STANDING_SIGN(BlockFactory.get(505, 0)),
    WARPED_STANDING_SIGN(BlockFactory.get(506, 0)),
    CRIMSON_WALL_SIGN(BlockFactory.get(507, 0)),
    WARPED_WALL_SIGN(BlockFactory.get(508, 0)),
    CRIMSON_STAIRS(BlockFactory.get(509, 0)),
    WARPED_STAIRS(BlockFactory.get(510, 0)),
    CRIMSON_FENCE(BlockFactory.get(511, 0)),
    WARPED_FENCE(BlockFactory.get(512, 0)),
    CRIMSON_FENCE_GATE(BlockFactory.get(513, 0)),
    WARPED_FENCE_GATE(BlockFactory.get(514, 0)),
    CRIMSON_BUTTON(BlockFactory.get(515, 0)),
    WARPED_BUTTON(BlockFactory.get(516, 0)),
    CRIMSON_PRESSURE_PLATE(BlockFactory.get(517, 0)),
    WARPED_PRESSURE_PLATE(BlockFactory.get(518, 0)),
    CRIMSON_SLAB(BlockFactory.get(519, 0)),
    WARPED_SLAB(BlockFactory.get(520, 0)),
    CRIMSON_DOUBLE_SLAB(BlockFactory.get(521, 0)),
    WARPED_DOUBLE_SLAB(BlockFactory.get(522, 0)),

    SOUL_TORCH(BlockFactory.get(523, 0)),
    SOUL_LANTERN(BlockFactory.get(524, 0)),

    BLOCK_OF_NETHERITE(BlockFactory.get(525, 0)),

    ANCIENT_DEBRIS(BlockFactory.get(526, 0)),
    RESPAWN_ANCHOR(BlockFactory.get(527, 0)),

    BLACKSTONE(BlockFactory.get(528, 0)),
    POLISHED_BLACKSTONE_BRICKS(BlockFactory.get(529, 0)),
    POLISHED_BLACKSTONE_BRICK_STAIRS(BlockFactory.get(530, 0)),
    BLACKSTONE_STAIRS(BlockFactory.get(531, 0)),
    BLACKSTONE_WALL(BlockFactory.get(532, 0)),
    POLISHED_BLACKSTONE_BRICK_WALL(BlockFactory.get(533, 0)),
    CHISELED_POLISHED_BLACKSTONE(BlockFactory.get(534, 0)),
    CRACKED_POLISHED_BLACKSTONE_BRICKS(BlockFactory.get(535, 0)),
    GILDED_BLACKSTONE(BlockFactory.get(536, 0)),
    BLACKSTONE_SLAB(BlockFactory.get(537, 0)),
    BLACKSTONE_DOUBLE_SLAB(BlockFactory.get(538, 0)),
    POLISHED_BLACKSTONE_BRICK_SLAB(BlockFactory.get(539, 0)),
    POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB(BlockFactory.get(540, 0)),

    CHAIN(BlockFactory.get(541, 0)),
    TWISTING_VINES(BlockFactory.get(542, 0)),
    NETHER_GOLD_ORE(BlockFactory.get(543, 0)),
    CRYING_OBSIDIAN(BlockFactory.get(544, 0)),
    SOUL_CAMPFIRE(BlockFactory.get(545, 0)),

    POLISHED_BLACKSTONE(BlockFactory.get(546, 0)),
    POLISHED_BLACKSTONE_STAIRS(BlockFactory.get(547, 0)),
    POLISHED_BLACKSTONE_SLAB(BlockFactory.get(548, 0)),
    POLISHED_BLACKSTONE_DOUBLE_SLAB(BlockFactory.get(549, 0)),

    POLISHED_BLACKSTONE_PRESSURE_PLATE(BlockFactory.get(550, 0)),
    POLISHED_BLACKSTONE_BUTTON(BlockFactory.get(551, 0)),
    POLISHED_BLACKSTONE_WALL(BlockFactory.get(552, 0)),

    WARPED_HYPHAE(BlockFactory.get(553, 0)),
    CRIMSON_HYPHAE(BlockFactory.get(554, 0)),
    STRIPPED_CRIMSON_HYPHAE(BlockFactory.get(555, 0)),
    STRIPPED_WARPED_HYPHAE(BlockFactory.get(556, 0)),

    CHISELED_NETHER_BRICKS(BlockFactory.get(557, 0)),
    CRACKED_NETHER_BRICKS(BlockFactory.get(558, 0)),
    QUARTZ_BRICKS(BlockFactory.get(559, 0)),

    UNKNOWN(BlockFactory.get(560, 0)),

    POWDER_SNOW(BlockFactory.get(561, 0)),
    SCULK_SENSOR(BlockFactory.get(562, 0)),
    POINTED_DRIPSTONE(BlockFactory.get(563, 0)),
    COPPER_ORE(BlockFactory.get(566, 0)),
    LIGHTNING_ROD(BlockFactory.get(567, 0)),
    DRIPSTONE_BLOCK(BlockFactory.get(572, 0)),

    ROOTED_DIRT(BlockFactory.get(573, 0)),
    HANGING_ROOTS(BlockFactory.get(574, 0)),
    MOSS_BLOCK(BlockFactory.get(575, 0)),
    SPORE_BLOSSOM(BlockFactory.get(576, 0)),
    CAVE_VINES(BlockFactory.get(577, 0)),
    BIG_DRIPLEAF(BlockFactory.get(578, 0)),
    AZALEA_LEAVES(BlockFactory.get(579, 0)),
    FLOWERED_AZALEA_LEAVES(BlockFactory.get(580, 0)),

    CALCITE(BlockFactory.get(581, 0)),

    BLOCK_OF_AMETHYST(BlockFactory.get(582, 0)),
    BUDDING_AMETHYST(BlockFactory.get(583, 0)),
    AMETHYST_CLUSTER(BlockFactory.get(584, 0)),
    LARGE_AMETHYST_BUD(BlockFactory.get(585, 0)),
    MEDIUM_AMETHYST_BUD(BlockFactory.get(586, 0)),
    SMALL_AMETHYST_BUD(BlockFactory.get(587, 0)),

    TUFF(BlockFactory.get(588, 0)),

    TINTED_GLASS(BlockFactory.get(589, 0)),

    MOSS_CARPET(BlockFactory.get(590, 0)),
    SMALL_DRIPLEAF(BlockFactory.get(591, 0)),
    AZALEA(BlockFactory.get(592, 0)),
    FLOWERING_AZALEA(BlockFactory.get(593, 0)),

    GLOW_FRAME(BlockFactory.get(594, 0)),

    COPPER_BLOCK(BlockFactory.get(595, 0)),

    EXPOSED_COPPER(BlockFactory.get(596, 0)),
    WEATHERED_COPPER(BlockFactory.get(597, 0)),
    OXIDIZED_COPPER(BlockFactory.get(598, 0)),

    WAXED_COPPER(BlockFactory.get(599, 0)),
    WAXED_EXPOSED_COPPER(BlockFactory.get(600, 0)),
    WAXED_WEATHERED_COPPER(BlockFactory.get(601, 0)),

    CUT_COPPER(BlockFactory.get(602, 0)),
    EXPOSED_CUT_COPPER(BlockFactory.get(603, 0)),
    WEATHERED_CUT_COPPER(BlockFactory.get(604, 0)),
    OXIDIZED_CUT_COPPER(BlockFactory.get(605, 0)),

    WAXED_CUT_COPPER(BlockFactory.get(606, 0)),
    WAXED_EXPOSED_CUT_COPPER(BlockFactory.get(607, 0)),
    WAXED_WEATHERED_CUT_COPPER(BlockFactory.get(608, 0)),

    CUT_COPPER_STAIRS(BlockFactory.get(609, 0)),
    EXPOSED_CUT_COPPER_STAIRS(BlockFactory.get(610, 0)),
    WEATHERED_CUT_COPPER_STAIRS(BlockFactory.get(611, 0)),
    OXIDIZED_CUT_COPPER_STAIRS(BlockFactory.get(612, 0)),
    WAXED_CUT_COPPER_STAIRS(BlockFactory.get(613, 0)),
    WAXED_EXPOSED_CUT_COPPER_STAIRS(BlockFactory.get(614, 0)),
    WAXED_WEATHERED_CUT_COPPER_STAIRS(BlockFactory.get(615, 0)),
    CUT_COPPER_SLAB(BlockFactory.get(616, 0)),
    EXPOSED_CUT_COPPER_SLAB(BlockFactory.get(617, 0)),
    WEATHERED_CUT_COPPER_SLAB(BlockFactory.get(618, 0)),
    OXIDIZED_CUT_COPPER_SLAB(BlockFactory.get(619, 0)),
    WAXED_CUT_COPPER_SLAB(BlockFactory.get(620, 0)),
    WAXED_EXPOSED_CUT_COPPER_SLAB(BlockFactory.get(621, 0)),
    WAXED_WEATHERED_CUT_COPPER_SLAB(BlockFactory.get(622, 0)),
    CUT_COPPER2(BlockFactory.get(623, 0)),

    // TODO: Know what is different from the basic block
    EXPOSED_CUT_COPPER2(BlockFactory.get(624, 0)),
    WEATHERED_CUT_COPPER2(BlockFactory.get(625, 0)),
    OXIDIZED_CUT_COPPER2(BlockFactory.get(626, 0)),
    WAXED_CUT_COPPER2(BlockFactory.get(627, 0)),
    WAXED_EXPOSED_CUT_COPPER2(BlockFactory.get(628, 0)),
    WAXED_WEATHERED_CUT_COPPER2(BlockFactory.get(629, 0)),

    CAVE_VINES_BODY_BERRIES(BlockFactory.get(630, 0)),
    CAVE_VINES_HEAD_BERRIES(BlockFactory.get(631, 0)),
    SMOOTH_BASALT(BlockFactory.get(632, 0)),
    DEEPSLATE(BlockFactory.get(633, 0)),
    COBBLED_DEEPSLATE(BlockFactory.get(634, 0)),
    COBBLED_DEEPSLATE_SLAB(BlockFactory.get(635, 0)),
    COBBLED_DEEPSLATE_STAIRS(BlockFactory.get(636, 0)),
    COBBLED_DEEPSLATE_WALL(BlockFactory.get(637, 0)),
    POLISHED_DEEPSLATE(BlockFactory.get(638, 0)),
    POLISHED_DEEPSLATE_SLAB(BlockFactory.get(639, 0)),
    POLISHED_DEEPSLATE_STAIRS(BlockFactory.get(640, 0)),
    POLISHED_DEEPSLATE_WALL(BlockFactory.get(641, 0)),
    DEEPSLATE_TILES(BlockFactory.get(642, 0)),
    DEEPSLATE_TILE_SLAB(BlockFactory.get(643, 0)),
    DEEPSLATE_TILE_STAIRS(BlockFactory.get(644, 0)),
    DEEPSLATE_TILE_WALL(BlockFactory.get(645, 0)),
    DEEPSLATE_BRICKS(BlockFactory.get(646, 0)),
    DEEPSLATE_BRICK_SLAB(BlockFactory.get(647, 0)),
    DEEPSLATE_BRICK_STAIRS(BlockFactory.get(648, 0)),
    DEEPSLATE_BRICK_WALL(BlockFactory.get(649, 0)),
    CHISELED_DEEPSLATE(BlockFactory.get(650, 0)),
    COBBLED_DEEPSLATE_DOUBLE_SLAB(BlockFactory.get(651, 0)),
    POLISHED_DEEPSLATE_DOUBLE_SLAB(BlockFactory.get(652, 0)),
    DEEPSLATE_TILE_DOUBLE_SLAB(BlockFactory.get(653, 0)),
    DEEPSLATE_BRICK_DOUBLE_SLAB(BlockFactory.get(654, 0)),
    DEEPSLATE_LAPIS_LAZULI_ORE(BlockFactory.get(655, 0)),
    DEEPSLATE_IRON_ORE(BlockFactory.get(656, 0)),
    DEEPSLATE_GOLD_ORE(BlockFactory.get(657, 0)),
    DEEPSLATE_REDSTONE_ORE(BlockFactory.get(658, 0)),
    LIT_DEEPSLATE_REDSTONE_ORE(BlockFactory.get(659, 0)),
    DEEPSLATE_DIAMOND_ORE(BlockFactory.get(660, 0)),
    DEEPSLATE_COAL_ORE(BlockFactory.get(661, 0)),
    DEEPSLATE_EMERALD_ORE(BlockFactory.get(662, 0)),
    DEEPSLATE_COPPER_ORE(BlockFactory.get(663, 0)),
    CRACKED_DEEPSLATE_TILES(BlockFactory.get(664, 0)),
    CRACKED_DEEPSLATE_BRICKS(BlockFactory.get(665, 0)),
    GLOW_LICHEN(BlockFactory.get(666, 0)),
    CANDLE(BlockFactory.get(667, 0)),
    WHITE_CANDLE(BlockFactory.get(668, 0)),
    ORANGE_CANDLE(BlockFactory.get(669, 0)),
    MAGENTA_CANDLE(BlockFactory.get(670, 0)),
    LIGHT_BLUE_CANDLE(BlockFactory.get(671, 0)),
    YELLOW_CANDLE(BlockFactory.get(672, 0)),
    LIME_CANDLE(BlockFactory.get(673, 0)),
    PINK_CANDLE(BlockFactory.get(674, 0)),
    GRAY_CANDLE(BlockFactory.get(675, 0)),
    LIGHT_GRAY_CANDLE(BlockFactory.get(676, 0)),
    CYAN_CANDLE(BlockFactory.get(677, 0)),
    PURPLE_CANDLE(BlockFactory.get(678, 0)),
    BLUE_CANDLE(BlockFactory.get(679, 0)),
    BROWN_CANDLE(BlockFactory.get(680, 0)),
    GREEN_CANDLE(BlockFactory.get(681, 0)),
    RED_CANDLE(BlockFactory.get(682, 0)),
    BLACK_CANDLE(BlockFactory.get(683, 0)),
    CANDLE_CAKE(BlockFactory.get(684, 0)),
    WHITE_CANDLE_CAKE(BlockFactory.get(685, 0)),
    ORANGE_CANDLE_CAKE(BlockFactory.get(686, 0)),
    MAGENTA_CANDLE_CAKE(BlockFactory.get(687, 0)),
    LIGHT_BLUE_CANDLE_CAKE(BlockFactory.get(688, 0)),
    YELLOW_CANDLE_CAKE(BlockFactory.get(689, 0)),
    LIME_CANDLE_CAKE(BlockFactory.get(690, 0)),
    PINK_CANDLE_CAKE(BlockFactory.get(691, 0)),
    GRAY_CANDLE_CAKE(BlockFactory.get(692, 0)),
    LIGHT_GRAY_CANDLE_CAKE(BlockFactory.get(693, 0)),
    CYAN_CANDLE_CAKE(BlockFactory.get(694, 0)),
    PURPLE_CANDLE_CAKE(BlockFactory.get(695, 0)),
    BLUE_CANDLE_CAKE(BlockFactory.get(696, 0)),
    BROWN_CANDLE_CAKE(BlockFactory.get(697, 0)),
    GREEN_CANDLE_CAKE(BlockFactory.get(698, 0)),
    RED_CANDLE_CAKE(BlockFactory.get(699, 0)),
    BLACK_CANDLE_CAKE(BlockFactory.get(700, 0)),
    WAXED_OXIDIZED_COPPER(BlockFactory.get(701, 0)),
    WAXED_OXIDIZED_CUT_COPPER(BlockFactory.get(702, 0)),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS(BlockFactory.get(703, 0)),
    WAXED_OXIDIZED_CUT_COPPER_SLAB(BlockFactory.get(704, 0)),
    WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB(BlockFactory.get(705, 0)),
    BLOCK_OF_RAW_IRON(BlockFactory.get(706, 0)),
    BLOCK_OF_RAW_COPPER(BlockFactory.get(707, 0)),
    BLOCK_OF_RAW_GOLD(BlockFactory.get(708, 0));

    companion object {
        @JvmStatic
        fun fromId(id: Int) = values().first { it.block.idInfo.blockId == id }

        @JvmStatic
        fun fromId(id: BlockIdentifier) = values().first { it.block.idInfo == id }
    }
}
