/**
 *
 * _  __           _    _
 * | |/ /___   ___ | | _(_) ___
 * | ' // _ \ / _ \| |/ / |/ _ \
 * | . \ (_) | (_) |   <| |  __/
 * |_|\_\___/ \___/|_|\_\_|\___|
 *
 * A server software for Minecraft: Bedrock Edition
 *
 * Copyright (C) 2021 organization Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package be.zvz.kookie.block

enum class VanillaBlocks(val id: Int, val meta: Int = 0) {
    AIR(0),
    STONE(1),
    GRANITE(1, 1),
    POLISHED_GRANITE(1, 2),
    DIORITE(1, 3),
    POLISHED_DIORITE(1, 4),
    ANDESITE(1, 5),
    POLISHED_ANDESITE(1, 6),
    GRASS(2),
    DIRT(3),
    COBBLESTONE(4),

    PLANKS(5),
    OAK_PLANKS(5, 0),
    SPRUCE_PLANKS(5, 1),
    BIRCH_PLANKS(5, 2),
    JUNGLE_PLANKS(5, 3),
    ACACIA_PLANKS(5, 4),
    DARK_OAK_PLANKS(5, 5),

    SAPLING(6),
    OAK_SAPLING(6, 0),
    SPRUCE_SAPLING(6, 1),
    BIRCH_SAPLING(6, 2),
    JUNGLE_SAPLING(6, 3),
    ACACIA_SAPLING(6, 4),
    DARK_OAK_SAPLING(6, 5),

    BEDROCK(7),

    FLOWING_WATER(8),
    WATER(9),
    FLOWING_LAVA(10),
    LAVA(11),

    SAND(12, 0),
    RED_SAND(12, 1),
    GRAVEL(13),
    GOLD_ORE(14),
    IRON_ORE(15),
    COAL_ORE(16),

    LOG(17),
    OAK_LOG(17, 0),
    SPRUCE_LOG(17, 1),
    BIRCH_LOG(17, 2),
    JUNGLE_LOG(17, 3),

    LEAVES(18),
    OAK_LEAVES(18, 0),
    SPRUCE_LEAVES(18, 1),
    BIRCH_LEAVES(18, 2),
    JUNGLE_LEAVES(18, 3),

    SPONGE(19),
    GLASS(20),

    LAPIS_LAZULI_ORE(21),
    LAPIS_LAZULI_BLOCK(22),

    DISPENSER(23),

    SANDSTONE(24, 0),
    CHISELED_SANDSTONE(24, 1),
    CUT_SANDSTONE(24, 2),
    SMOOTH_SANDSTONE(24, 3),

    NOTE_BLOCK(25),
    BED(26),

    POWERED_RAIL(27),
    DETECTOR_RAIL(28),
    STICKY_PISTON(29),

    COBWEB(30),

    TALL_GRASS(31, 1),
    FERN(31, 2),
    DEAD_BUSH(32),

    PISTON(33),
    PISTON_HEAD(34),

    WOOL(35),
    WHITE_WOOL(35, 0),
    ORANGE_WOOL(35, 1),
    MAGENTA_WOOL(35, 2),
    LIGHT_BLUE_WOOL(35, 3),
    YELLOW_WOOL(35, 4),
    LIME_WOOL(35, 5),
    PINK_WOOL(35, 6),
    GRAY_WOOL(35, 7),
    LIGHT_GRAY_WOOL(35, 8),
    CYAN_WOOL(35, 9),
    PURPLE_WOOL(35, 10),
    BLUE_WOOL(35, 11),
    BROWN_WOOL(35, 12),
    GREEN_WOOL(35, 13),
    RED_WOOL(35, 14),
    BLACK_WOOL(35, 15),

    @Deprecated("Aliased", ReplaceWith("UNKNOWN_ELEMENT"))
    ELEMENT_0(36),
    UNKNOWN_ELEMENT(36),

    @Deprecated("Aliased", ReplaceWith("DANDELION"))
    YELLOW_FLOWER(37),
    DANDELION(37),

    @Deprecated("Aliased", ReplaceWith("POPPY"))
    RED_FLOWER(38),
    POPPY(38, 0),
    BLUE_ORCHID(38, 1),
    ALLIUM(38, 2),
    AZURE_BLUET(38, 3),
    RED_TULIP(38, 4),
    ORANGE_TULIP(38, 5),
    WHITE_TULIP(38, 6),
    PINK_TULIP(38, 7),
    OXEYE_DAISY(38, 8),
    CORNFLOWER(38, 9),
    LILY_OF_THE_VALLEY(38, 10),

    BROWN_MUSHROOM(39),
    RED_MUSHROOM(40),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_GOLD"))
    GOLD_BLOCK(41),
    BLOCK_OF_GOLD(41),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_IRON"))
    IRON_BLOCK(42),
    BLOCK_OF_IRON(42),

    DOUBLE_STONE_SLAB(43),
    SMOOTH_STONE_SLAB(44, 0),
    SANDSTONE_SLAB(44, 1),
    FAKE_WOODEN_SLAB(44, 2),
    COBBLESTONE_SLAB(44, 3),
    BRICK_SLAB(44, 4),
    STONE_BRICK_SLAB(44, 5),
    QUARTZ_SLAB(44, 6),
    NETHER_BRICK_SLAB(44, 7),

    BRICK_BLOCK(45),
    TNT(46),
    BOOKSHELF(47),
    MOSSY_COBBLESTONE(48),
    OBSIDIAN(49),
    TORCH(50, 5),
    FIRE(51),
    SPAWNER(52),
    OAK_STAIRS(53),
    CHEST(54, 2),
    REDSTONE_WIRE(55),
    DIAMOND_ORE(56),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_DIAMOND"))
    DIAMOND_BLOCK(57),
    BLOCK_OF_DIAMOND(57),

    CRAFTING_TABLE(58),
    WHEAT_CROPS(59),
    FARMLAND(60),

    FURNACE(61, 2),
    LIT_FURNACE(62, 2),

    @Deprecated("Aliased", ReplaceWith("OAK_STANDING_SIGN"))
    OAK_SIGN(63),
    OAK_STANDING_SIGN(63),

    OAK_DOOR(64),
    LADDER(65, 2),
    RAIL(66),
    COBBLESTONE_STAIRS(67),
    OAK_WALL_SIGN(68, 2),
    LEVER(69),
    STONE_PRESSURE_PLATE(70),
    IRON_DOOR(71),
    OAK_PRESSURE_PLATE(72),
    REDSTONE_ORE(73),

    @Deprecated("Aliased", ReplaceWith("GLOWING_REDSTONE_ORE"))
    LIT_REDSTONE_ORE(74),
    GLOWING_REDSTONE_ORE(74),

    UNLIT_REDSTONE_TORCH(75),
    REDSTONE_TORCH(76, 5),

    STONE_BUTTON(77),
    SNOW_LAYER(78),
    ICE(79),
    SNOW(80),
    CACTUS(81),
    CLAY(82),
    SUGAR_CANE(83),
    JUKEBOX(84),

    FENCE(85),
    OAK_FENCE(85, 0),
    SPRUCE_FENCE(85, 1),
    BIRCH_FENCE(85, 2),
    JUNGLE_FENCE(85, 3),
    ACACIA_FENCE(85, 4),
    DARK_OAK_FENCE(85, 5),

    PUMPKIN(86),
    NETHERRACK(87),
    SOUL_SAND(88),
    GLOWSTONE(89),
    PORTAL(90),
    NETHER_PORTAL(90, 1),

    @Deprecated("Aliased", ReplaceWith("JACK_O_LANTERN"))
    LIT_PUMPKIN(91),
    JACK_O_LANTERN(91),
    CAKE(92),

    @Deprecated("Aliased", ReplaceWith("UNPOWERED_REPEATER"))
    REDSTONE_REPEATER(93),
    UNPOWERED_REPEATER(93),
    POWERED_REPEATER(94),

    INVISIBLE_BEDROCK(95),
    OAK_TRAPDOOR(96),

    INFESTED_STONE(97, 0),
    INFESTED_COBBLESTONE(97, 1),
    INFESTED_STONE_BRICKS(97, 2),
    INFESTED_MOSSY_STONE_BRICKS(97, 3),
    INFESTED_CRACKED_STONE_BRICKS(97, 4),
    INFESTED_CHISELED_STONE_BRICKS(97, 5),
    INFESTED_DEEPSLATE(97, 6),

    STONE_BRICKS(98, 0),
    MOSSY_STONE_BRICKS(98, 1),
    CRACKED_STONE_BRICKS(98, 2),
    CHISELED_STONE_BRICKS(98, 3),
    SMOOTH_STONE_BRICKS(98, 4),

    BROWN_MUSHROOM_BLOCK(99, 0),
    MUSHROOM_STEM(99, 10),
    ALL_SIDED_MUSHROOM_STEM(99, 15),
    RED_MUSHROOM_BLOCK(100),

    IRON_BARS(101),
    GLASS_PANE(102),
    MELON(103),
    PUMPKIN_STEM(104),
    MELON_STEM(105),
    VINES(106),
    OAK_FENCE_GATE(107),
    BRICK_STAIRS(108),
    STONE_BRICK_STAIRS(109),
    MYCELIUM(110),
    LILY_PAD(111),
    NETHER_BRICK(112),
    NETHER_BRICK_FENCE(113),
    NETHER_BRICK_STAIRS(114),
    NETHER_WART(115),
    ENCHANTING_TABLE(116),
    BREWING_STAND(117),
    CAULDRON(118),
    END_PORTAL(119),
    END_PORTAL_FRAME(120),
    END_STONE(121),
    DRAGON_EGG(122),
    REDSTONE_LAMP(123),
    LIT_REDSTONE_LAMP(124),
    DROPPER(125),
    ACTIVATOR_RAIL(126),
    COCOA(127),
    SANDSTONE_STAIRS(128),
    EMERALD_ORE(129),
    ENDER_CHEST(130, 2),
    TRIPWIRE_HOOK(131),
    TRIPWIRE(132),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_EMERALD"))
    EMERALD_BLOCK(133),
    BLOCK_OF_EMERALD(133),

    SPRUCE_STAIRS(134),
    BIRCH_STAIRS(135),
    JUNGLE_STAIRS(136),
    COMMAND_BLOCK(137),
    BEACON(138),

    COBBLESTONE_WALL(139, 0),
    MOSSY_COBBLESTONE_WALL(139, 1),
    GRANITE_WALL(139, 2),
    DIORITE_WALL(139, 3),
    ANDESITE_WALL(139, 4),
    SANDSTONE_WALL(139, 5),
    BRICK_WALL(139, 6),
    STONE_BRICK_WALL(139, 7),
    MOSSY_STONE_BRICK_WALL(139, 8),
    NETHER_BRICK_WALL(139, 9),
    END_STONE_BRICK_WALL(139, 10),
    PRISMARINE_WALL(139, 11),
    RED_SANDSTONE_WALL(139, 12),
    RED_NETHER_BRICK_WALL(139, 13),

    FLOWER_POT(140),
    CARROTS(141),
    POTATOES(142),
    OAK_BUTTON(143),

    @Deprecated("Aliased", ReplaceWith("HEAD"))
    SKULL(144, 2),
    HEAD(144, 2),

    ANVIL(145),
    TRAPPED_CHEST(146, 2),

    LIGHT_WEIGHTED_PRESSURE_PLATE(147),
    HEAVY_WEIGHTED_PRESSURE_PLATE(148),

    UNPOWERED_COMPARATOR(149),
    POWERED_COMPARATOR(150),

    DAYLIGHT_DETECTOR(151),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_REDSTONE"))
    REDSTONE_BLOCK(152),
    BLOCK_OF_REDSTONE(152),

    NETHER_QUARTZ_ORE(153),
    HOPPER(154),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_QUARTZ"))
    QUARTZ_BLOCK(155),
    BLOCK_OF_QUARTZ(155, 0),

    CHISELED_QUARTZ_BLOCK(155, 1),
    PILLAR_QUARTZ_BLOCK(155, 2),
    SMOOTH_QUARTZ_BLOCK(155, 3),

    QUARTZ_STAIRS(156),

    DOUBLE_OAK_SLAB(157),
    OAK_SLAB(158, 0),
    SPRUCE_SLAB(158, 1),
    BIRCH_SLAB(158, 2),
    JUNGLE_SLAB(158, 3),
    ACACIA_SLAB(158, 4),
    DARK_OAK_SLAB(158, 5),

    @Deprecated("Aliased", ReplaceWith("COLORED_TERRACOTTA"))
    STAINED_HARDENED_CLAY(159),
    COLORED_TERRACOTTA(159),

    WHITE_TERRACOTTA(159, 0),
    ORANGE_TERRACOTTA(159, 1),
    MAGENTA_TERRACOTTA(159, 2),
    LIGHT_BLUE_TERRACOTTA(159, 3),
    YELLOW_TERRACOTTA(159, 4),
    LIME_TERRACOTTA(159, 5),
    PINK_TERRACOTTA(159, 6),
    GRAY_TERRACOTTA(159, 7),
    LIGHT_GRAY_TERRACOTTA(159, 8),
    CYAN_TERRACOTTA(159, 9),
    PURPLE_TERRACOTTA(159, 10),
    BLUE_TERRACOTTA(159, 11),
    BROWN_TERRACOTTA(159, 12),
    GREEN_TERRACOTTA(159, 13),
    RED_TERRACOTTA(159, 14),
    BLACK_TERRACOTTA(159, 15),

    STAINED_GLASS_PANE(160),
    WHITE_STAINED_GLASS_PANE(160, 0),
    ORANGE_STAINED_GLASS_PANE(160, 1),
    MAGENTA_STAINED_GLASS_PANE(160, 2),
    LIGHT_BLUE_STAINED_GLASS_PANE(160, 3),
    YELLOW_STAINED_GLASS_PANE(160, 4),
    LIME_STAINED_GLASS_PANE(160, 5),
    PINK_STAINED_GLASS_PANE(160, 6),
    GRAY_STAINED_GLASS_PANE(160, 7),
    LIGHT_GRAY_STAINED_GLASS_PANE(160, 8),
    CYAN_STAINED_GLASS_PANE(160, 9),
    PURPLE_STAINED_GLASS_PANE(160, 10),
    BLUE_STAINED_GLASS_PANE(160, 11),
    BROWN_STAINED_GLASS_PANE(160, 12),
    GREEN_STAINED_GLASS_PANE(160, 13),
    RED_STAINED_GLASS_PANE(160, 14),
    BLACK_STAINED_GLASS_PANE(160, 15),

    LEAVES2(161),
    ACACIA_LEAVES(161, 0),
    DARK_OAK_LEAVES(161, 1),

    LOG2(162),
    ACACIA_LOG(162, 0),
    DARK_OAK_LOG(162, 1),

    ACACIA_STAIRS(163),
    DARK_OAK_STAIRS(164),
    SLIME_BLOCK(165),
    GLOW_STICK(166),
    IRON_TRAPDOOR(167),

    PRISMARINE(168, 0),
    DARK_PRISMARINE(168, 1),
    PRISMARINE_BRICKS(168, 2),

    SEA_LANTERN(169),

    @Deprecated("Aliased", ReplaceWith("HAY_BALE"))
    HAY_BLOCK(170),
    HAY_BALE(170),

    CARPET(171),
    WHITE_CARPET(171, 0),
    ORANGE_CARPET(171, 1),
    MAGENTA_CARPET(171, 2),
    LIGHT_BLUE_CARPET(171, 3),
    YELLOW_CARPET(171, 4),
    LIME_CARPET(171, 5),
    PINK_CARPET(171, 6),
    GRAY_CARPET(171, 7),
    LIGHT_GRAY_CARPET(171, 8),
    CYAN_CARPET(171, 9),
    PURPLE_CARPET(171, 10),
    BLUE_CARPET(171, 11),
    BROWN_CARPET(171, 12),
    GREEN_CARPET(171, 13),
    RED_CARPET(171, 14),
    BLACK_CARPET(171, 15),

    HARDENED_CLAY(172),

    @Deprecated("Aliased", ReplaceWith("BLOCK_OF_COAL"))
    COAL_BLOCK(173),
    BLOCK_OF_COAL(173),

    PACKED_ICE(174),

    DOUBLE_PLANT(175),
    SUNFLOWER(175, 0),
    LILAC(175, 1),
    DOUBLE_TALLGRASS(175, 2),
    LARGE_FERN(175, 3),
    ROSE_BUSH(175, 4),
    PEONY(175, 5),

    STANDING_BANNER(176),
    WALL_BANNER(177, 2),

    INVERTED_DAYLIGHT_DETECTOR(178),

    RED_SANDSTONE(179, 0),
    CHISELED_RED_SANDSTONE(179, 1),
    CUT_RED_SANDSTONE(179, 2),
    SMOOTH_RED_SANDSTONE(179, 3),

    RED_SANDSTONE_STAIRS(180),
    DOUBLE_RED_SANDSTONE(181),

    STONE_SLAB2(182),
    RED_SANDSTONE_SLAB(182, 0),
    PURPUR_SLAB(182, 1),
    PRISMARINE_SLAB(182, 2),
    DARK_PRISMARINE_SLAB(182, 3),
    PRISMARINE_BRICKS_SLAB(182, 4),
    MOSSY_COBBLESTONE_SLAB(182, 5),
    SMOOTH_SANDSTONE_SLAB(182, 6),
    RED_NETHER_BRICK_SLAB(182, 7),

    SPRUCE_FENCE_GATE(183),
    BIRCH_FENCE_GATE(184),
    JUNGLE_FENCE_GATE(185),
    DARK_OAK_FENCE_GATE(186),
    ACACIA_FENCE_GATE(187),
    REPEATING_COMMAND_BLOCK(188),
    CHAIN_COMMAND_BLOCK(189),

    HARDENED_GLASS_PANE(190),
    WHITE_HARDENED_GLASS_PANE(190, 0),
    ORANGE_HARDENED_GLASS_PANE(190, 1),
    MAGENTA_HARDENED_GLASS_PANE(190, 2),
    LIGHT_BLUE_HARDENED_GLASS_PANE(190, 3),
    YELLOW_HARDENED_GLASS_PANE(190, 4),
    LIME_HARDENED_GLASS_PANE(190, 5),
    PINK_HARDENED_GLASS_PANE(190, 6),
    GRAY_HARDENED_GLASS_PANE(190, 7),
    LIGHT_GRAY_HARDENED_GLASS_PANE(190, 8),
    CYAN_HARDENED_GLASS_PANE(190, 9),
    PURPLE_HARDENED_GLASS_PANE(190, 10),
    BLUE_HARDENED_GLASS_PANE(190, 11),
    BROWN_HARDENED_GLASS_PANE(190, 12),
    GREEN_HARDENED_GLASS_PANE(190, 13),
    RED_HARDENED_GLASS_PANE(190, 14),
    BLACK_HARDENED_GLASS_PANE(190, 15),

    HARDENED_STAINED_GLASS_PANE(191),
    WHITE_HARDENED_STAINED_GLASS_PANE(191, 0),
    ORANGE_HARDENED_STAINED_GLASS_PANE(191, 1),
    MAGENTA_HARDENED_STAINED_GLASS_PANE(191, 2),
    LIGHT_BLUE_HARDENED_STAINED_GLASS_PANE(191, 3),
    YELLOW_HARDENED_STAINED_GLASS_PANE(191, 4),
    LIME_HARDENED_STAINED_GLASS_PANE(191, 5),
    PINK_HARDENED_STAINED_GLASS_PANE(191, 6),
    GRAY_HARDENED_STAINED_GLASS_PANE(191, 7),
    LIGHT_GRAY_HARDENED_STAINED_GLASS_PANE(191, 8),
    CYAN_HARDENED_STAINED_GLASS_PANE(191, 9),
    PURPLE_HARDENED_STAINED_GLASS_PANE(191, 10),
    BLUE_HARDENED_STAINED_GLASS_PANE(191, 11),
    BROWN_HARDENED_STAINED_GLASS_PANE(191, 12),
    GREEN_HARDENED_STAINED_GLASS_PANE(191, 13),
    RED_HARDENED_STAINED_GLASS_PANE(191, 14),
    BLACK_HARDENED_STAINED_GLASS_PANE(191, 15),

    HEAT_BLOCK(192),

    SPRUCE_DOOR(193),
    BIRCH_DOOR(194),
    JUNGLE_DOOR(195),
    ACACIA_DOOR(196),
    DARK_OAK_DOOR(197),
    GRASS_PATH(198),
    ITEM_FRAME(199),

    CHORUS_FLOWER(200),
    PURPUR_BLOCK(201, 0),
    CHISELED_PURPUR(201, 2),
    PURPUR_PILLAR_UP_DOWN(201, 2),
    SMOOTH_PURPUR(201, 3),
    PURPUR_PILLAR_EAST_WEST(201, 6),
    PURPUR_PILLAR_NORTH_SOUTH(201, 10),

    RED_TORCH(202, 5),
    GREEN_TORCH(202, 13),
    PURPUR_STAIRS(203),
    BLUE_TORCH(204, 5),
    PURPLE_TORCH(204, 13),

    UNDYED_SHULKER_BOX(205),
    WHITE_UNDYED_SHULKER_BOX(205, 0),
    ORANGE_UNDYED_SHULKER_BOX(205, 1),
    MAGENTA_UNDYED_SHULKER_BOX(205, 2),
    LIGHT_BLUE_UNDYED_SHULKER_BOX(205, 3),
    YELLOW_UNDYED_SHULKER_BOX(205, 4),
    LIME_UNDYED_SHULKER_BOX(205, 5),
    PINK_UNDYED_SHULKER_BOX(205, 6),
    GRAY_UNDYED_SHULKER_BOX(205, 7),
    LIGHT_GRAY_UNDYED_SHULKER_BOX(205, 8),
    CYAN_UNDYED_SHULKER_BOX(205, 9),
    PURPLE_UNDYED_SHULKER_BOX(205, 10),
    BLUE_UNDYED_SHULKER_BOX(205, 11),
    BROWN_UNDYED_SHULKER_BOX(205, 12),
    GREEN_UNDYED_SHULKER_BOX(205, 13),
    RED_UNDYED_SHULKER_BOX(205, 14),
    BLACK_UNDYED_SHULKER_BOX(205, 15),

    END_STONE_BRICKS(206),
    FROSTED_ICE(207),
    END_ROD(208),
    END_GATEWAY(209),

    ALLOW(210),
    DENY(211),
    BORDER(212),

    MAGMA_BLOCK(213),
    NETHER_WART_BLOCK(214),
    RED_NETHER_BRICK(215),
    BONE_BLOCK(216),
    STRUCTURE_VOID(217),

    SHULKER_BOX(218),
    WHITE_SHULKER_BOX(218, 0),
    ORANGE_SHULKER_BOX(218, 1),
    MAGENTA_SHULKER_BOX(218, 2),
    LIGHT_BLUE_SHULKER_BOX(218, 3),
    YELLOW_SHULKER_BOX(218, 4),
    LIME_SHULKER_BOX(218, 5),
    PINK_SHULKER_BOX(218, 6),
    GRAY_SHULKER_BOX(218, 7),
    LIGHT_GRAY_SHULKER_BOX(218, 8),
    CYAN_SHULKER_BOX(218, 9),
    PURPLE_SHULKER_BOX(218, 10),
    BLUE_SHULKER_BOX(218, 11),
    BROWN_SHULKER_BOX(218, 12),
    GREEN_SHULKER_BOX(218, 13),
    RED_SHULKER_BOX(218, 14),
    BLACK_SHULKER_BOX(218, 15),

    PURPLE_GLAZED_TERRACOTTA(219, 2),
    WHITE_GLAZED_TERRACOTTA(220, 2),
    ORANGE_GLAZED_TERRACOTTA(221, 2),
    MAGENTA_GLAZED_TERRACOTTA(222, 2),
    LIGHT_BLUE_GLAZED_TERRACOTTA(223, 2),
    YELLOW_GLAZED_TERRACOTTA(224, 2),
    LIME_GLAZED_TERRACOTTA(225, 2),
    PINK_GLAZED_TERRACOTTA(226, 2),
    GRAY_GLAZED_TERRACOTTA(227, 2),
    LIGHT_GRAY_GLAZED_TERRACOTTA(228, 2),
    CYAN_GLAZED_TERRACOTTA(229, 2),
    CHALKBOARD(230),
    BLUE_GLAZED_TERRACOTTA(231, 2),
    BROWN_GLAZED_TERRACOTTA(232, 2),
    GREEN_GLAZED_TERRACOTTA(233, 2),
    RED_GLAZED_TERRACOTTA(234, 2),
    BLACK_GLAZED_TERRACOTTA(235, 2),

    CONCRETE(236),
    WHITE_CONCRETE(236, 0),
    ORANGE_CONCRETE(236, 1),
    MAGENTA_CONCRETE(236, 2),
    LIGHT_BLUE_CONCRETE(236, 3),
    YELLOW_CONCRETE(236, 4),
    LIME_CONCRETE(236, 5),
    PINK_CONCRETE(236, 6),
    GRAY_CONCRETE(236, 7),
    LIGHT_GRAY_CONCRETE(236, 8),
    CYAN_CONCRETE(236, 9),
    PURPLE_CONCRETE(236, 10),
    BLUE_CONCRETE(236, 11),
    BROWN_CONCRETE(236, 12),
    GREEN_CONCRETE(236, 13),
    RED_CONCRETE(236, 14),
    BLACK_CONCRETE(236, 15),

    CONCRETE_POWDER(237),
    WHITE_CONCRETE_POWDER(237, 0),
    ORANGE_CONCRETE_POWDER(237, 1),
    MAGENTA_CONCRETE_POWDER(237, 2),
    LIGHT_BLUE_CONCRETE_POWDER(237, 3),
    YELLOW_CONCRETE_POWDER(237, 4),
    LIME_CONCRETE_POWDER(237, 5),
    PINK_CONCRETE_POWDER(237, 6),
    GRAY_CONCRETE_POWDER(237, 7),
    LIGHT_GRAY_CONCRETE_POWDER(237, 8),
    CYAN_CONCRETE_POWDER(237, 9),
    PURPLE_CONCRETE_POWDER(237, 10),
    BLUE_CONCRETE_POWDER(237, 11),
    BROWN_CONCRETE_POWDER(237, 12),
    GREEN_CONCRETE_POWDER(237, 13),
    RED_CONCRETE_POWDER(237, 14),
    BLACK_CONCRETE_POWDER(237, 15),

    CHEMISTRY_TABLE(238),
    COMPOUND_CREATOR(238, 0),
    MATERIAL_REDUCER(238, 4),
    ELEMENT_CONSTRUCTOR(238, 8),
    LAB_TABLE(238, 12),

    UNDERWATER_TORCH(239, 5),
    CHORUS_PLANT(240),

    STAINED_GLASS(241),
    WHITE_STAINED_GLASS(241, 0),
    ORANGE_STAINED_GLASS(241, 1),
    MAGENTA_STAINED_GLASS(241, 2),
    LIGHT_BLUE_STAINED_GLASS(241, 3),
    YELLOW_STAINED_GLASS(241, 4),
    LIME_STAINED_GLASS(241, 5),
    PINK_STAINED_GLASS(241, 6),
    GRAY_STAINED_GLASS(241, 7),
    LIGHT_GRAY_STAINED_GLASS(241, 8),
    CYAN_STAINED_GLASS(241, 9),
    PURPLE_STAINED_GLASS(241, 10),
    BLUE_STAINED_GLASS(241, 11),
    BROWN_STAINED_GLASS(241, 12),
    GREEN_STAINED_GLASS(241, 13),
    RED_STAINED_GLASS(241, 14),
    BLACK_STAINED_GLASS(241, 15),

    PODZOL(243),
    BEETROOTS(244),
    STONECUTTER(245),
    GLOWING_OBSIDIAN(246),
    NETHER_REACTOR_CORE(247),
    INFO_UPDATE(248),
    INFO_UPDATE2(249),

    @Deprecated("Aliased", ReplaceWith("MOVING_PISTON"))
    MOVING_BLOCK(250),
    MOVING_PISTON(250),

    OBSERVER(251),

    STRUCTURE_BLOCK(252),
    STRUCTURE_BLOCK_DATA(252, 0),
    STRUCTURE_BLOCK_SAVE(252, 1),
    STRUCTURE_BLOCK_LOAD(252, 2),
    STRUCTURE_BLOCK_CORNER(252, 3),
    STRUCTURE_BLOCK_INVALID(252, 4),
    STRUCTURE_BLOCK_EXPORT(252, 5),

    HARDENED_GLASS(253),
    WHITE_HARDENED_GLASS(253, 0),
    ORANGE_HARDENED_GLASS(253, 1),
    MAGENTA_HARDENED_GLASS(253, 2),
    LIGHT_BLUE_HARDENED_GLASS(253, 3),
    YELLOW_HARDENED_GLASS(253, 4),
    LIME_HARDENED_GLASS(253, 5),
    PINK_HARDENED_GLASS(253, 6),
    GRAY_HARDENED_GLASS(253, 7),
    LIGHT_GRAY_HARDENED_GLASS(253, 8),
    CYAN_HARDENED_GLASS(253, 9),
    PURPLE_HARDENED_GLASS(253, 10),
    BLUE_HARDENED_GLASS(253, 11),
    BROWN_HARDENED_GLASS(253, 12),
    GREEN_HARDENED_GLASS(253, 13),
    RED_HARDENED_GLASS(253, 14),
    BLACK_HARDENED_GLASS(253, 15),

    HARDENED_STAINED_GLASS(254),
    WHITE_HARDENED_STAINED_GLASS(254, 0),
    ORANGE_HARDENED_STAINED_GLASS(254, 1),
    MAGENTA_HARDENED_STAINED_GLASS(254, 2),
    LIGHT_BLUE_HARDENED_STAINED_GLASS(254, 3),
    YELLOW_HARDENED_STAINED_GLASS(254, 4),
    LIME_HARDENED_STAINED_GLASS(254, 5),
    PINK_HARDENED_STAINED_GLASS(254, 6),
    GRAY_HARDENED_STAINED_GLASS(254, 7),
    LIGHT_GRAY_HARDENED_STAINED_GLASS(254, 8),
    CYAN_HARDENED_STAINED_GLASS(254, 9),
    PURPLE_HARDENED_STAINED_GLASS(254, 10),
    BLUE_HARDENED_STAINED_GLASS(254, 11),
    BROWN_HARDENED_STAINED_GLASS(254, 12),
    GREEN_HARDENED_STAINED_GLASS(254, 13),
    RED_HARDENED_STAINED_GLASS(254, 14),
    BLACK_HARDENED_STAINED_GLASS(254, 15),

    RESERVED6(255),

    PRISMARINE_STAIRS(257),
    DARK_PRISMARINE_STAIRS(258),
    PRISMARINE_BRICKS_STAIRS(259),

    STRIPPED_SPRUCE_LOG(260),
    STRIPPED_BIRCH_LOG(261),
    STRIPPED_JUNGLE_LOG(262),
    STRIPPED_ACACIA_LOG(263),
    STRIPPED_DARK_OAK_LOG(264),
    STRIPPED_OAK_LOG(265),

    BLUE_ICE(266),
    ELEMENT_1(267),
    ELEMENT_HYDROGEN(267),
    ELEMENT_2(268),
    ELEMENT_HELIUM(268),
    ELEMENT_3(269),
    ELEMENT_LITHIUM(269),
    ELEMENT_4(270),
    ELEMENT_BERYLLIUM(270),
    ELEMENT_5(271),
    ELEMENT_BORON(271),
    ELEMENT_6(272),
    ELEMENT_CARBON(272),
    ELEMENT_7(273),
    ELEMENT_NITROGEN(273),
    ELEMENT_8(274),
    ELEMENT_OXYGEN(274),
    ELEMENT_9(275),
    ELEMENT_FLUORINE(275),
    ELEMENT_10(276),
    ELEMENT_NEON(276),
    ELEMENT_11(277),
    ELEMENT_SODIUM(277),
    ELEMENT_12(278),
    ELEMENT_MAGNESIUM(278),
    ELEMENT_13(279),
    ELEMENT_ALUMINUM(279),
    ELEMENT_14(280),
    ELEMENT_SILICON(280),
    ELEMENT_15(281),
    ELEMENT_PHOSPHORUS(281),
    ELEMENT_16(282),
    ELEMENT_SULFUR(282),
    ELEMENT_17(283),
    ELEMENT_CHLORINE(283),
    ELEMENT_18(284),
    ELEMENT_ARGON(284),
    ELEMENT_19(285),
    ELEMENT_POTASSIUM(285),
    ELEMENT_20(286),
    ELEMENT_CALCIUM(286),
    ELEMENT_21(287),
    ELEMENT_SCANDIUM(287),
    ELEMENT_22(288),
    ELEMENT_TITANIUM(288),
    ELEMENT_23(289),
    ELEMENT_VANADIUM(289),
    ELEMENT_24(290),
    ELEMENT_CHROMIUM(290),
    ELEMENT_25(291),
    ELEMENT_MANGANESE(291),
    ELEMENT_26(292),
    ELEMENT_IRON(292),
    ELEMENT_27(293),
    ELEMENT_COBALT(293),
    ELEMENT_28(294),
    ELEMENT_NICKEL(294),
    ELEMENT_29(295),
    ELEMENT_COPPER(295),
    ELEMENT_30(296),
    ELEMENT_ZINC(296),
    ELEMENT_31(297),
    ELEMENT_GALLIUM(297),
    ELEMENT_32(298),
    ELEMENT_GERMANIUM(298),
    ELEMENT_33(299),
    ELEMENT_ARSENIC(299),
    ELEMENT_34(300),
    ELEMENT_SELENIUM(300),
    ELEMENT_35(301),
    ELEMENT_BROMINE(301),
    ELEMENT_36(302),
    ELEMENT_KRYPTON(302),
    ELEMENT_37(303),
    ELEMENT_RUBIDIUM(303),
    ELEMENT_38(304),
    ELEMENT_STRONTIUM(304),
    ELEMENT_39(305),
    ELEMENT_YTTRIUM(305),
    ELEMENT_40(306),
    ELEMENT_ZIRCONIUM(306),
    ELEMENT_41(307),
    ELEMENT_NIOBIUM(307),
    ELEMENT_42(308),
    ELEMENT_MOLYBDENUM(308),
    ELEMENT_43(309),
    ELEMENT_TECHNETIUM(309),
    ELEMENT_44(310),
    ELEMENT_RUTHENIUM(310),
    ELEMENT_45(311),
    ELEMENT_RHODIUM(311),
    ELEMENT_46(312),
    ELEMENT_PALLADIUM(312),
    ELEMENT_47(313),
    ELEMENT_SILVER(313),
    ELEMENT_48(314),
    ELEMENT_CADMIUM(314),
    ELEMENT_49(315),
    ELEMENT_INDIUM(315),
    ELEMENT_50(316),
    ELEMENT_TIN(316),
    ELEMENT_51(317),
    ELEMENT_ANTIMONY(317),
    ELEMENT_52(318),
    ELEMENT_TELLURIUM(318),
    ELEMENT_53(319),
    ELEMENT_IODINE(319),
    ELEMENT_54(320),
    ELEMENT_XENON(320),
    ELEMENT_55(321),
    ELEMENT_CESIUM(321),
    ELEMENT_56(322),
    ELEMENT_BARIUM(322),
    ELEMENT_57(323),
    ELEMENT_LANTHANUM(323),
    ELEMENT_58(324),
    ELEMENT_CERIUM(324),
    ELEMENT_59(325),
    ELEMENT_PRASEODYMIUM(325),
    ELEMENT_60(326),
    ELEMENT_NEODYMIUM(326),
    ELEMENT_61(327),
    ELEMENT_PROMETHIUM(327),
    ELEMENT_62(328),
    ELEMENT_SAMARIUM(328),
    ELEMENT_63(329),
    ELEMENT_EUROPIUM(329),
    ELEMENT_64(330),
    ELEMENT_GADOLINIUM(330),
    ELEMENT_65(331),
    ELEMENT_TERBIUM(331),
    ELEMENT_66(332),
    ELEMENT_DYSPROSIUM(332),
    ELEMENT_67(333),
    ELEMENT_HOLMIUM(333),
    ELEMENT_68(334),
    ELEMENT_ERBIUM(334),
    ELEMENT_69(335),
    ELEMENT_THULIUM(335),
    ELEMENT_70(336),
    ELEMENT_YTTERBIUM(336),
    ELEMENT_71(337),
    ELEMENT_LUTETIUM(337),
    ELEMENT_72(338),
    ELEMENT_HAFNIUM(338),
    ELEMENT_73(339),
    ELEMENT_TANTALUM(339),
    ELEMENT_74(340),
    ELEMENT_TUNGSTEN(340),
    ELEMENT_75(341),
    ELEMENT_RHENIUM(341),
    ELEMENT_76(342),
    ELEMENT_OSMIUM(342),
    ELEMENT_77(343),
    ELEMENT_IRIDIUM(343),
    ELEMENT_78(344),
    ELEMENT_PLATINUM(344),
    ELEMENT_79(345),
    ELEMENT_GOLD(345),
    ELEMENT_80(346),
    ELEMENT_MERCURY(346),
    ELEMENT_81(347),
    ELEMENT_THALLIUM(347),
    ELEMENT_82(348),
    ELEMENT_LEAD(348),
    ELEMENT_83(349),
    ELEMENT_BISMUTH(349),
    ELEMENT_84(350),
    ELEMENT_POLONIUM(350),
    ELEMENT_85(351),
    ELEMENT_ASTATINE(351),
    ELEMENT_86(352),
    ELEMENT_RADON(352),
    ELEMENT_87(353),
    ELEMENT_FRANCIUM(353),
    ELEMENT_88(354),
    ELEMENT_RADIUM(354),
    ELEMENT_89(355),
    ELEMENT_ACTINIUM(355),
    ELEMENT_90(356),
    ELEMENT_THORIUM(356),
    ELEMENT_91(357),
    ELEMENT_PROTACTINIUM(357),
    ELEMENT_92(358),
    ELEMENT_URANIUM(358),
    ELEMENT_93(359),
    ELEMENT_NEPTUNIUM(359),
    ELEMENT_94(360),
    ELEMENT_PLUTONIUM(360),
    ELEMENT_95(361),
    ELEMENT_AMERICIUM(361),
    ELEMENT_96(362),
    ELEMENT_CURIUM(362),
    ELEMENT_97(363),
    ELEMENT_BERKELIUM(363),
    ELEMENT_98(364),
    ELEMENT_CALIFORNIUM(364),
    ELEMENT_99(365),
    ELEMENT_EINSTEINIUM(365),
    ELEMENT_100(366),
    ELEMENT_FERMIUM(366),
    ELEMENT_101(367),
    ELEMENT_MENDELEVIUM(367),
    ELEMENT_102(368),
    ELEMENT_NOBELIUM(368),
    ELEMENT_103(369),
    ELEMENT_LAWRENCIUM(369),
    ELEMENT_104(370),
    ELEMENT_RUTHERFORDIUM(370),
    ELEMENT_105(371),
    ELEMENT_DUBNIUM(371),
    ELEMENT_106(372),
    ELEMENT_SEABORGIUM(372),
    ELEMENT_107(373),
    ELEMENT_BOHRIUM(373),
    ELEMENT_108(374),
    ELEMENT_HASSIUM(374),
    ELEMENT_109(375),
    ELEMENT_MEITNERIUM(375),
    ELEMENT_110(376),
    ELEMENT_DARMSTADTIUM(376),
    ELEMENT_111(377),
    ELEMENT_ROENTGENIUM(377),
    ELEMENT_112(378),
    ELEMENT_COPERNICIUM(378),
    ELEMENT_113(379),
    ELEMENT_NIHONIUM(379),
    ELEMENT_114(380),
    ELEMENT_FLEROVIUM(380),
    ELEMENT_115(381),
    ELEMENT_MOSCOVIUM(381),
    ELEMENT_116(382),
    ELEMENT_LIVERMORIUM(382),
    ELEMENT_117(383),
    ELEMENT_TENNESSINE(383),
    ELEMENT_118(384),
    ELEMENT_OGANESSON(384),

    SEAGRASS(385),

    CORAL(386),
    TUBE_CORAL(386, 0),
    BRAIN_CORAL(386, 1),
    BUBBLE_CORAL(386, 2),
    FIRE_CORAL(386, 3),
    HORN_CORAL(386, 4),
    DEAD_TUBE_CORAL(386, 8),
    DEAD_BRAIN_CORAL(386, 9),
    DEAD_BUBBLE_CORAL(386, 10),
    DEAD_FIRE_CORAL(386, 11),
    DEAD_HORN_CORAL(386, 12),

    CORAL_BLOCK(387),
    TUBE_CORAL_BLOCK(387, 0),
    BRAIN_CORAL_BLOCK(387, 1),
    BUBBLE_CORAL_BLOCK(387, 2),
    FIRE_CORAL_BLOCK(387, 3),
    HORN_CORAL_BLOCK(387, 4),
    DEAD_TUBE_CORAL_BLOCK(387, 8),
    DEAD_BRAIN_CORAL_BLOCK(387, 9),
    DEAD_BUBBLE_CORAL_BLOCK(387, 10),
    DEAD_FIRE_CORAL_BLOCK(387, 11),
    DEAD_HORN_CORAL_BLOCK(387, 12),

    CORAL_FAN(388),
    TUBE_CORAL_FAN(388, 0),
    BRAIN_CORAL_FAN(388, 1),
    BUBBLE_CORAL_FAN(388, 2),
    FIRE_CORAL_FAN(388, 3),
    HORN_CORAL_FAN(388, 4),

    DEAD_CORAL_FAN(389),
    DEAD_TUBE_CORAL_FAN(389, 0),
    DEAD_BRAIN_CORAL_FAN(389, 1),
    DEAD_BUBBLE_CORAL_FAN_(389, 2),
    DEAD_FIRE_CORAL_FAN(389, 3),
    DEAD_HORN_CORAL_FAN(389, 4),

    CORAL_WALL_FAN(390),
    TUBE_CORAL_WALL_FAN(390, 0),
    BRAIN_CORAL_WALL_FAN(390, 1),
    DEAD_TUBE_CORAL_WALL_FAN(390, 2),
    DEAD_BRAIN_CORAL_WALL_FAN(390, 3),

    CORAL_WALL_FAN2(391),
    BUBBLE_CORAL_WALL_FAN(391, 0),
    FIRE_CORAL_WALL_FAN(391, 1),
    DEAD_BUBBLE_CORAL_WALL_FAN(391, 2),
    DEAD_FIRE_CORAL_WALL_FAN(391, 3),

    CORAL_WALL_FAN3(392),
    HORN_CORAL_WALL_FAN(392, 0),
    DEAD_HORN_CORAL_WALL_FAN(392, 2),

    KELP(393),
    DRIED_KELP_BLOCK(394),

    ACACIA_BUTTON(395),
    BIRCH_BUTTON(396),
    DARK_OAK_BUTTON(397),
    JUNGLE_BUTTON(398),
    SPRUCE_BUTTON(399),

    ACACIA_TRAPDOOR(400),
    BIRCH_TRAPDOOR(401),
    DARK_OAK_TRAPDOOR(402),
    JUNGLE_TRAPDOOR(403),
    SPRUCE_TRAPDOOR(404),

    ACACIA_PRESSURE_PLATE(405),
    BIRCH_PRESSURE_PLATE(406),
    DARK_OAK_PRESSURE_PLATE(407),
    JUNGLE_PRESSURE_PLATE(408),
    SPRUCE_PRESSURE_PLATE(409),

    CARVED_PUMPKIN(410),
    SEA_PICKLE(411),
    CONDUIT(412),
    SEE_TURTLE_EGG(414),

    BUBBLE_COLUMN_DOWN(415),
    BUBBLE_COLUMN_UP(415, 1),

    BARRIER(416),

    STONE_SLAB3(417),
    END_STONE_BRICK_SLAB(417, 0),
    SMOOTH_RED_SANDSTONE_SLAB(417, 1),
    POLISHED_ANDESITE_SLAB(417, 2),
    ANDESITE_SLAB(417, 3),
    DIORITE_SLAB(417, 4),
    POLISHED_DIORITE_SLAB(417, 5),
    GRANITE_SLAB(417, 6),
    POLISHED_GRANITE_SLAB(417, 7),

    BAMBOO(418),
    BAMBOO_SAPLING(419),
    SCAFFOLDING(420),

    STONE_SLAB4(421),
    MOSSY_STONE_BRICK_SLAB(421, 0),
    SMOOTH_QUARTZ_SLAB(421, 1),
    STONE_SLAB(421, 2),
    CUT_SANDSTONE_SLAB(421, 3),
    CUT_RED_SANDSTONE_SLAB(421, 4),

    DOUBLE_END_STONE_SLAB(422),
    DOUBLE_MOSSY_STONE_SLAB(423),

    GRANITE_STAIRS(424),
    DIORITE_STAIRS(425),
    ANDESITE_STAIRS(426),
    POLISHED_GRANITE_STAIRS(427),
    POLISHED_DIORITE_STAIRS(428),
    POLISHED_ANDESITE_STAIRS(429),
    MOSSY_STONE_BRICK_STAIRS(430),
    SMOOTH_RED_SANDSTONE_STAIRS(431),
    SMOOTH_SANDSTONE_STAIRS(432),
    END_STONE_BRICK_STAIRS(433),
    MOSSY_COBBLESTONE_STAIRS(434),
    STONE_STAIRS(435),

    @Deprecated("Aliased", ReplaceWith("SPRUCE_STANDING_SIGN"))
    SPRUCE_SIGN(436),
    SPRUCE_STANDING_SIGN(436),
    SPRUCE_WALL_SIGN(437, 2),

    SMOOTH_STONE(438),

    RED_NETHER_BRICK_STAIRS(439),
    SMOOTH_QUARTZ_STAIRS(440),

    @Deprecated("Aliased", ReplaceWith("BIRCH_STANDING_SIGN"))
    BIRCH_SIGN(441),
    BIRCH_STANDING_SIGN(441),
    BIRCH_WALL_SIGN(442, 2),

    @Deprecated("Aliased", ReplaceWith("JUNGLE_STANDING_SIGN"))
    JUNGLE_SIGN(443),
    JUNGLE_STANDING_SIGN(443),
    JUNGLE_WALL_SIGN(444, 2),

    @Deprecated("Aliased", ReplaceWith("ACACIA_STANDING_SIGN"))
    ACACIA_SIGN(445),
    ACACIA_STANDING_SIGN(445),
    ACACIA_WALL_SIGN(446, 2),

    @Deprecated("Aliased", ReplaceWith("DARK_OAK_STANDING_SIGN"))
    DARK_OAK_SIGN(447),
    DARK_OAK_STANDING_SIGN(447),
    DARK_OAK_WALL_SIGN(448, 2),

    LECTERN(449),
    GRINDSTONE(450),
    BLAST_FURNACE(451),
    STONECUTTER_BLOCK(452),
    SMOKER(453),
    LIT_SMOKER(454),
    CARTOGRAPHY_TABLE(455),
    FLETCHING_TABLE(456),
    SMITHING_TABLE(457),
    BARREL(458),
    LOOM(459),
    BELL(461),
    SWEET_BERRY_BUSH(462),
    LANTERN(463),
    CAMPFIRE(464),
    LAVA_CAULDRON(465),
    JIGSAW(466),

    WOOD(467),
    OAK_WOOD(467, 0),
    SPRUCE_WOOD(467, 1),
    BIRCH_WOOD(467, 2),
    JUNGLE_WOOD(467, 3),
    ACACIA_WOOD(467, 4),
    DARK_OAK_WOOD(467, 5),
    STRIPPED_OAK_WOOD(467, 8),
    STRIPPED_SPRUCE_WOOD(467, 9),
    STRIPPED_BIRCH_WOOD(467, 10),
    STRIPPED_JUNGLE_WOOD(467, 11),
    STRIPPED_ACACIA_WOOD(467, 12),
    STRIPPED_DARK_OAK_WOOD(467, 13),

    COMPOSTER(468),
    LIT_BLAST_FURNACE(469),
    LIGHT_BLOCK(470),
    WITHER_ROSE(471),
    STICKY_PISTON_HEAD(472),

    BEE_NEST(473),
    BEEHIVE(474),
    HONEY_BLOCK(475),
    HONEYCOMB_BLOCK(476),

    LODESTONE(477),

    CRIMSON_ROOTS(478),
    WARPED_ROOTS(479),
    CRIMSON_STEM(480),
    WARPED_STEM(481),
    WARPED_WART_BLOCK(482),
    CRIMSON_FUNGUS(483),
    WARPED_FUNGUS(484),

    SHROOMLIGHT(485),
    WEEPING_VINES(486),

    CRIMSON_NYLIUM(487),
    WARPED_NYLIUM(488),

    BASALT(489),
    POLISHED_BASALT(490),

    SOUL_SOIL(491),
    SOUL_FIRE(492),

    NETHER_SPROUTS(493),
    TARGET(494),

    STRIPPED_CRIMSON_STEM(495),
    STRIPPED_WARPED_STEM(496),
    CRIMSON_PLANKS(497),
    WARPED_PLANKS(498),
    CRIMSON_DOOR(499),
    WARPED_DOOR(500),
    CRIMSON_TRAPDOOR(501),
    WARPED_TRAPDOOR(502),

    @Deprecated("Aliased", ReplaceWith("CRIMSON_STANDING_SIGN"))
    CRIMSON_SIGN(505),
    CRIMSON_STANDING_SIGN(505),

    @Deprecated("Aliased", ReplaceWith("WARPED_STANDING_SIGN"))
    WARPED_SIGN(506),
    WARPED_STANDING_SIGN(506),

    CRIMSON_WALL_SIGN(507),
    WARPED_WALL_SIGN(508),
    CRIMSON_STAIRS(509),
    WARPED_STAIRS(510),
    CRIMSON_FENCE(511),
    WARPED_FENCE(512),
    CRIMSON_FENCE_GATE(513),
    WARPED_FENCE_GATE(514),
    CRIMSON_BUTTON(515),
    WARPED_BUTTON(516),
    CRIMSON_PRESSURE_PLATE(517),
    WARPED_PRESSURE_PLATE(518),
    CRIMSON_SLAB(519),
    WARPED_SLAB(520),
    CRIMSON_DOUBLE_SLAB(521),
    WARPED_DOUBLE_SLAB(522),

    SOUL_TORCH(523),
    SOUL_LANTERN(524),

    BLOCK_OF_NETHERITE(525),

    ANCIENT_DEBRIS(526),
    RESPAWN_ANCHOR(527),

    BLACKSTONE(528),
    POLISHED_BLACKSTONE_BRICKS(529),
    POLISHED_BLACKSTONE_BRICK_STAIRS(530),
    BLACKSTONE_STAIRS(531),
    BLACKSTONE_WALL(532),
    POLISHED_BLACKSTONE_BRICK_WALL(533),
    CHISELED_POLISHED_BLACKSTONE(534),
    CRACKED_POLISHED_BLACKSTONE_BRICKS(535),
    GILDED_BLACKSTONE(536),
    BLACKSTONE_SLAB(537),
    BLACKSTONE_DOUBLE_SLAB(538),
    POLISHED_BLACKSTONE_BRICK_SLAB(539),
    POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB(540),

    CHAIN(541),
    TWISTING_VINES(542),
    NETHER_GOLD_ORE(543),
    CRYING_OBSIDIAN(544),
    SOUL_CAMPFIRE(545),

    POLISHED_BLACKSTONE(546),
    POLISHED_BLACKSTONE_STAIRS(547),
    POLISHED_BLACKSTONE_SLAB(548),
    POLISHED_BLACKSTONE_DOUBLE_SLAB(549),

    POLISHED_BLACKSTONE_PRESSURE_PLATE(550),
    POLISHED_BLACKSTONE_BUTTON(551),
    POLISHED_BLACKSTONE_WALL(552),

    WARPED_HYPHAE(553),
    CRIMSON_HYPHAE(554),
    STRIPPED_CRIMSON_HYPHAE(555),
    STRIPPED_WARPED_HYPHAE(556),

    CHISELED_NETHER_BRICKS(557),
    CRACKED_NETHER_BRICKS(558),
    QUARTZ_BRICKS(559),

    UNKNOWN(560),

    POWDER_SNOW(561),
    SCULK_SENSOR(562),
    POINTED_DRIPSTONE(563),
    COPPER_ORE(566),
    LIGHTNING_ROD(567),
    DRIPSTONE_BLOCK(572),

    ROOTED_DIRT(573),
    HANGING_ROOTS(574),
    MOSS_BLOCK(575),
    SPORE_BLOSSOM(576),
    CAVE_VINES(577),
    BIG_DRIPLEAF(578),
    AZALEA_LEAVES(579),
    FLOWERED_AZALEA_LEAVES(580),

    CALCITE(581),

    BLOCK_OF_AMETHYST(582),
    BUDDING_AMETHYST(583),
    AMETHYST_CLUSTER(584),
    LARGE_AMETHYST_BUD(585),
    MEDIUM_AMETHYST_BUD(586),
    SMALL_AMETHYST_BUD(587),

    TUFF(588),

    TINTED_GLASS(589),

    MOSS_CARPET(590),
    SMALL_DRIPLEAF(591),
    AZALEA(592),
    FLOWERING_AZALEA(593),

    GLOW_FRAME(594),

    COPPER_BLOCK(595),

    EXPOSED_COPPER(596),
    WEATHERED_COPPER(597),
    OXIDIZED_COPPER(598),

    WAXED_COPPER(599),
    WAXED_EXPOSED_COPPER(600),
    WAXED_WEATHERED_COPPER(601),

    CUT_COPPER(602),
    EXPOSED_CUT_COPPER(603),
    WEATHERED_CUT_COPPER(604),
    OXIDIZED_CUT_COPPER(605),

    WAXED_CUT_COPPER(606),
    WAXED_EXPOSED_CUT_COPPER(607),
    WAXED_WEATHERED_CUT_COPPER(608),

    CUT_COPPER_STAIRS(609),
    EXPOSED_CUT_COPPER_STAIRS(610),
    WEATHERED_CUT_COPPER_STAIRS(611),
    OXIDIZED_CUT_COPPER_STAIRS(612),
    WAXED_CUT_COPPER_STAIRS(613),
    WAXED_EXPOSED_CUT_COPPER_STAIRS(614),
    WAXED_WEATHERED_CUT_COPPER_STAIRS(615),
    CUT_COPPER_SLAB(616),
    EXPOSED_CUT_COPPER_SLAB(617),
    WEATHERED_CUT_COPPER_SLAB(618),
    OXIDIZED_CUT_COPPER_SLAB(619),
    WAXED_CUT_COPPER_SLAB(620),
    WAXED_EXPOSED_CUT_COPPER_SLAB(621),
    WAXED_WEATHERED_CUT_COPPER_SLAB(622),
    CUT_COPPER2(623),

    // TODO: Know what is different from the basic block
    EXPOSED_CUT_COPPER2(624),
    WEATHERED_CUT_COPPER2(625),
    OXIDIZED_CUT_COPPER2(626),
    WAXED_CUT_COPPER2(627),
    WAXED_EXPOSED_CUT_COPPER2(628),
    WAXED_WEATHERED_CUT_COPPER2(629),

    CAVE_VINES_BODY_BERRIES(630),
    CAVE_VINES_HEAD_BERRIES(631),
    SMOOTH_BASALT(632),
    DEEPSLATE(633),
    COBBLED_DEEPSLATE(634),
    COBBLED_DEEPSLATE_SLAB(635),
    COBBLED_DEEPSLATE_STAIRS(636),
    COBBLED_DEEPSLATE_WALL(637),
    POLISHED_DEEPSLATE(638),
    POLISHED_DEEPSLATE_SLAB(639),
    POLISHED_DEEPSLATE_STAIRS(640),
    POLISHED_DEEPSLATE_WALL(641),
    DEEPSLATE_TILES(642),
    DEEPSLATE_TILE_SLAB(643),
    DEEPSLATE_TILE_STAIRS(644),
    DEEPSLATE_TILE_WALL(645),
    DEEPSLATE_BRICKS(646),
    DEEPSLATE_BRICK_SLAB(647),
    DEEPSLATE_BRICK_STAIRS(648),
    DEEPSLATE_BRICK_WALL(649),
    CHISELED_DEEPSLATE(650),
    COBBLED_DEEPSLATE_DOUBLE_SLAB(651),
    POLISHED_DEEPSLATE_DOUBLE_SLAB(652),
    DEEPSLATE_TILE_DOUBLE_SLAB(653),
    DEEPSLATE_BRICK_DOUBLE_SLAB(654),
    DEEPSLATE_LAPIS_LAZULI_ORE(655),
    DEEPSLATE_IRON_ORE(656),
    DEEPSLATE_GOLD_ORE(657),
    DEEPSLATE_REDSTONE_ORE(658),
    LIT_DEEPSLATE_REDSTONE_ORE(659),
    DEEPSLATE_DIAMOND_ORE(660),
    DEEPSLATE_COAL_ORE(661),
    DEEPSLATE_EMERALD_ORE(662),
    DEEPSLATE_COPPER_ORE(663),
    CRACKED_DEEPSLATE_TILES(664),
    CRACKED_DEEPSLATE_BRICKS(665),
    GLOW_LICHEN(666),
    CANDLE(667),
    WHITE_CANDLE(668),
    ORANGE_CANDLE(669),
    MAGENTA_CANDLE(670),
    LIGHT_BLUE_CANDLE(671),
    YELLOW_CANDLE(672),
    LIME_CANDLE(673),
    PINK_CANDLE(674),
    GRAY_CANDLE(675),
    LIGHT_GRAY_CANDLE(676),
    CYAN_CANDLE(677),
    PURPLE_CANDLE(678),
    BLUE_CANDLE(679),
    BROWN_CANDLE(680),
    GREEN_CANDLE(681),
    RED_CANDLE(682),
    BLACK_CANDLE(683),
    CANDLE_CAKE(684),
    WHITE_CANDLE_CAKE(685),
    ORANGE_CANDLE_CAKE(686),
    MAGENTA_CANDLE_CAKE(687),
    LIGHT_BLUE_CANDLE_CAKE(688),
    YELLOW_CANDLE_CAKE(689),
    LIME_CANDLE_CAKE(690),
    PINK_CANDLE_CAKE(691),
    GRAY_CANDLE_CAKE(692),
    LIGHT_GRAY_CANDLE_CAKE(693),
    CYAN_CANDLE_CAKE(694),
    PURPLE_CANDLE_CAKE(695),
    BLUE_CANDLE_CAKE(696),
    BROWN_CANDLE_CAKE(697),
    GREEN_CANDLE_CAKE(698),
    RED_CANDLE_CAKE(699),
    BLACK_CANDLE_CAKE(700),
    WAXED_OXIDIZED_COPPER(701),
    WAXED_OXIDIZED_CUT_COPPER(702),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS(703),
    WAXED_OXIDIZED_CUT_COPPER_SLAB(704),
    WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB(705),
    BLOCK_OF_RAW_IRON(706),
    BLOCK_OF_RAW_COPPER(707),
    BLOCK_OF_RAW_GOLD(708);

    val identifier: BlockIdentifier = BlockIdentifier(this.id, this.meta)
    val fullId: Int = (id shr 4) or meta
    val block: Block get() = BlockFactory.get(id, meta)
    // TODO: Add val runtimeId, after implementing RuntimeBlockMapping

    companion object {
        const val ANVIL_NORMAL = 0
        const val ANVIL_SLIGHTLY_DAMAGED = 4
        const val ANVIL_VERY_DAMAGED = 8
        const val BAMBOO_FLAG_THICK = 1
        const val BAMBOO_FLAG_READY = 8
        const val BAMBOO_LEAF_SIZE_SHIFT = 1
        const val BAMBOO_LEAF_SIZE_MASK = 3
        const val BARREL_FLAG_OPEN = 8
        const val BED_FLAG_HEAD = 8
        const val BED_FLAG_OCCUPIED = 4
        const val BEDROCK_FLAG_INFINIBURN = 1
        const val BREWING_STAND_FLAG_EAST = 1
        const val BREWING_STAND_FLAG_SOUTHWEST = 2
        const val BREWING_STAND_FLAG_NORTHWEST = 4
        const val BUTTON_FLAG_POWERED = 8
        const val CHEMISTRY_COMPOUND_CREATOR = 0
        const val CHEMISTRY_MATERIAL_REDUCER = 4
        const val CHEMISTRY_ELEMENT_CONSTRUCTOR = 8
        const val CHEMISTRY_LAB_TABLE = 12
        const val COLORED_TORCH_BP_BLUE = 0
        const val COLORED_TORCH_BP_PURPLE = 8
        const val COLORED_TORCH_RG_RED = 0
        const val COLORED_TORCH_RG_GREEN = 8
        const val CORAL_BLOCK_FLAG_DEAD = 8
        const val CORAL_FAN_EAST_WEST = 0
        const val CORAL_FAN_NORTH_SOUTH = 1
        const val CORAL_FAN_HANG_FLAG_DEAD = 2
        const val CORAL_FAN_HANG_TUBE = 0
        const val CORAL_FAN_HANG_BRAIN = 1
        const val CORAL_FAN_HANG2_BUBBLE = 0
        const val CORAL_FAN_HANG2_FIRE = 1
        const val CORAL_FAN_HANG3_HORN = 0
        const val CORAL_VARIANT_TUBE = 0
        const val CORAL_VARIANT_BRAIN = 1
        const val CORAL_VARIANT_BUBBLE = 2
        const val CORAL_VARIANT_FIRE = 3
        const val CORAL_VARIANT_HORN = 4
        const val DIRT_NORMAL = 0
        const val DIRT_COARSE = 1
        const val DOOR_FLAG_TOP = 8
        const val DOOR_BOTTOM_FLAG_OPEN = 4
        const val DOOR_TOP_FLAG_RIGHT = 1
        const val DOOR_TOP_FLAG_POWERED = 2
        const val DOUBLE_PLANT_SUNFLOWER = 0
        const val DOUBLE_PLANT_LILAC = 1
        const val DOUBLE_PLANT_TALLGRASS = 2
        const val DOUBLE_PLANT_LARGE_FERN = 3
        const val DOUBLE_PLANT_ROSE_BUSH = 4
        const val DOUBLE_PLANT_PEONY = 5
        const val DOUBLE_PLANT_FLAG_TOP = 8
        const val END_PORTAL_FRAME_FLAG_EYE = 4
        const val FENCE_GATE_FLAG_OPEN = 4
        const val FENCE_GATE_FLAG_IN_WALL = 8
        const val FLOWER_POPPY = 0
        const val FLOWER_BLUE_ORCHID = 1
        const val FLOWER_ALLIUM = 2
        const val FLOWER_AZURE_BLUET = 3
        const val FLOWER_RED_TULIP = 4
        const val FLOWER_ORANGE_TULIP = 5
        const val FLOWER_WHITE_TULIP = 6
        const val FLOWER_PINK_TULIP = 7
        const val FLOWER_OXEYE_DAISY = 8
        const val FLOWER_CORNFLOWER = 9
        const val FLOWER_LILY_OF_THE_VALLEY = 10
        const val FLOWER_POT_FLAG_OCCUPIED = 1
        const val HOPPER_FLAG_POWERED = 8
        const val INFESTED_STONE = 0
        const val INFESTED_COBBLESTONE = 1
        const val INFESTED_STONE_BRICK = 2
        const val INFESTED_STONE_BRICK_MOSSY = 3
        const val INFESTED_STONE_BRICK_CRACKED = 4
        const val INFESTED_STONE_BRICK_CHISELED = 5
        const val ITEM_FRAME_FLAG_HAS_MAP = 4
        const val LANTERN_FLAG_HANGING = 1
        const val LEAVES_FLAG_NO_DECAY = 4
        const val LEAVES_FLAG_CHECK_DECAY = 8
        const val LEVER_FLAG_POWERED = 8
        const val LIQUID_FLAG_FALLING = 8
        const val MUSHROOM_BLOCK_ALL_PORES = 0
        const val MUSHROOM_BLOCK_CAP_NORTHWEST_CORNER = 1
        const val MUSHROOM_BLOCK_CAP_NORTH_SIDE = 2
        const val MUSHROOM_BLOCK_CAP_NORTHEAST_CORNER = 3
        const val MUSHROOM_BLOCK_CAP_WEST_SIDE = 4
        const val MUSHROOM_BLOCK_CAP_TOP_ONLY = 5
        const val MUSHROOM_BLOCK_CAP_EAST_SIDE = 6
        const val MUSHROOM_BLOCK_CAP_SOUTHWEST_CORNER = 7
        const val MUSHROOM_BLOCK_CAP_SOUTH_SIDE = 8
        const val MUSHROOM_BLOCK_CAP_SOUTHEAST_CORNER = 9
        const val MUSHROOM_BLOCK_STEM = 10
        const val MUSHROOM_BLOCK_ALL_CAP = 14
        const val MUSHROOM_BLOCK_ALL_STEM = 15
        const val NETHER_PORTAL_AXIS_X = 1
        const val NETHER_PORTAL_AXIS_Z = 2
        const val NETHER_REACTOR_INACTIVE = 0
        const val NETHER_REACTOR_ACTIVE = 1
        const val NETHER_REACTOR_USED = 2
        const val PRESSURE_PLATE_FLAG_POWERED = 1
        const val PRISMARINE_NORMAL = 0
        const val PRISMARINE_DARK = 1
        const val PRISMARINE_BRICKS = 2
        const val PURPUR_NORMAL = 0
        const val PURPUR_PILLAR = 2
        const val QUARTZ_NORMAL = 0
        const val QUARTZ_CHISELED = 1
        const val QUARTZ_PILLAR = 2
        const val QUARTZ_SMOOTH = 3
        const val RAIL_STRAIGHT_NORTH_SOUTH = 0
        const val RAIL_STRAIGHT_EAST_WEST = 1
        const val RAIL_ASCENDING_EAST = 2
        const val RAIL_ASCENDING_WEST = 3
        const val RAIL_ASCENDING_NORTH = 4
        const val RAIL_ASCENDING_SOUTH = 5
        const val RAIL_CURVE_SOUTHEAST = 6
        const val RAIL_CURVE_SOUTHWEST = 7
        const val RAIL_CURVE_NORTHWEST = 8
        const val RAIL_CURVE_NORTHEAST = 9
        const val REDSTONE_COMPARATOR_FLAG_SUBTRACT = 4
        const val REDSTONE_COMPARATOR_FLAG_POWERED = 8
        const val REDSTONE_RAIL_FLAG_POWERED = 8
        const val SANDSTONE_NORMAL = 0
        const val SANDSTONE_CHISELED = 1
        const val SANDSTONE_CUT = 2
        const val SANDSTONE_SMOOTH = 3
        const val SAPLING_FLAG_READY = 8
        const val SEA_PICKLE_FLAG_NOT_UNDERWATER = 4
        const val SLAB_FLAG_UPPER = 8
        const val SPONGE_FLAG_WET = 1
        const val STAIR_FLAG_UPSIDE_DOWN = 4
        const val STONE_NORMAL = 0
        const val STONE_GRANITE = 1
        const val STONE_POLISHED_GRANITE = 2
        const val STONE_DIORITE = 3
        const val STONE_POLISHED_DIORITE = 4
        const val STONE_ANDESITE = 5
        const val STONE_POLISHED_ANDESITE = 6
        const val STONE_BRICK_NORMAL = 0
        const val STONE_BRICK_MOSSY = 1
        const val STONE_BRICK_CRACKED = 2
        const val STONE_BRICK_CHISELED = 3
        const val STONE_SLAB_SMOOTH_STONE = 0
        const val STONE_SLAB_SANDSTONE = 1
        const val STONE_SLAB_FAKE_WOODEN = 2
        const val STONE_SLAB_COBBLESTONE = 3
        const val STONE_SLAB_BRICK = 4
        const val STONE_SLAB_STONE_BRICK = 5
        const val STONE_SLAB_QUARTZ = 6
        const val STONE_SLAB_NETHER_BRICK = 7
        const val STONE_SLAB2_RED_SANDSTONE = 0
        const val STONE_SLAB2_PURPUR = 1
        const val STONE_SLAB2_PRISMARINE = 2
        const val STONE_SLAB2_DARK_PRISMARINE = 3
        const val STONE_SLAB2_PRISMARINE_BRICKS = 4
        const val STONE_SLAB2_MOSSY_COBBLESTONE = 5
        const val STONE_SLAB2_SMOOTH_SANDSTONE = 6
        const val STONE_SLAB2_RED_NETHER_BRICK = 7
        const val STONE_SLAB3_END_STONE_BRICK = 0
        const val STONE_SLAB3_SMOOTH_RED_SANDSTONE = 1
        const val STONE_SLAB3_POLISHED_ANDESITE = 2
        const val STONE_SLAB3_ANDESITE = 3
        const val STONE_SLAB3_DIORITE = 4
        const val STONE_SLAB3_POLISHED_DIORITE = 5
        const val STONE_SLAB3_GRANITE = 6
        const val STONE_SLAB3_POLISHED_GRANITE = 7
        const val STONE_SLAB4_MOSSY_STONE_BRICK = 0
        const val STONE_SLAB4_SMOOTH_QUARTZ = 1
        const val STONE_SLAB4_STONE = 2
        const val STONE_SLAB4_CUT_SANDSTONE = 3
        const val STONE_SLAB4_CUT_RED_SANDSTONE = 4
        const val TALLGRASS_NORMAL = 1
        const val TALLGRASS_FERN = 2
        const val TNT_FLAG_UNSTABLE = 1
        const val TNT_FLAG_UNDERWATER = 2
        const val TRAPDOOR_FLAG_UPPER = 4
        const val TRAPDOOR_FLAG_OPEN = 8
        const val TRIPWIRE_FLAG_TRIGGERED = 1
        const val TRIPWIRE_FLAG_SUSPENDED = 2
        const val TRIPWIRE_FLAG_CONNECTED = 4
        const val TRIPWIRE_FLAG_DISARMED = 8
        const val TRIPWIRE_HOOK_FLAG_CONNECTED = 4
        const val TRIPWIRE_HOOK_FLAG_POWERED = 8
        const val VINE_FLAG_SOUTH = 1
        const val VINE_FLAG_WEST = 2
        const val VINE_FLAG_NORTH = 4
        const val VINE_FLAG_EAST = 8
        const val WALL_COBBLESTONE = 0
        const val WALL_MOSSY_COBBLESTONE = 1
        const val WALL_GRANITE = 2
        const val WALL_DIORITE = 3
        const val WALL_ANDESITE = 4
        const val WALL_SANDSTONE = 5
        const val WALL_BRICK = 6
        const val WALL_STONE_BRICK = 7
        const val WALL_MOSSY_STONE_BRICK = 8
        const val WALL_NETHER_BRICK = 9
        const val WALL_END_STONE_BRICK = 10
        const val WALL_PRISMARINE = 11
        const val WALL_RED_SANDSTONE = 12
        const val WALL_RED_NETHER_BRICK = 13

        @JvmStatic
        @JvmOverloads
        fun fromId(id: Int, meta: Int? = null) = values().firstOrNull { it.id == id && (meta == null || it.meta == meta) }

        @JvmStatic
        fun fromId(id: BlockIdentifier) = fromId(id.blockId, id.variant) ?: values().first { it.id == id.blockId }
    }
}
